#   --- Improt ---
import json
from PyQt5.QtWidgets import (
    QSizePolicy
)
from PyQt5.QtCore import (
    Qt,
    QSize
)
from PyQt5.QtGui import (
    QPixmap,
    QIcon,
    QPainter
)
from PyQt5.QtSvg import (
    QSvgRenderer
)

def StockUi(self):
    self.TitleL.setObjectName('TitleL')
    self.ScrollS.setObjectName('ScrollS')
    self.WidgetW.setObjectName('WidgetW')
    self.FundamentalDataTitleL.setObjectName('FundamentalDataTitleL')
    self.IndicatorsSubTitleL.setObjectName('IndicatorsSubTitleL')
    self.MarketCapNameL.setObjectName('MarketCapNameL')
    self.MarketCapValueL.setObjectName('MarketCapValueL')
    self.PENameL.setObjectName('PENameL')
    self.PEValueL.setObjectName('PEValueL')
    self.ForwardPENameL.setObjectName('ForwardPENameL')
    self.ForwardPEValueL.setObjectName('ForwardPEValueL')
    self.PEGNameL.setObjectName('PEGNameL')
    self.PEGValueL.setObjectName('PEGValueL')
    self.PBNameL.setObjectName('PBNameL')
    self.PBValueL.setObjectName('PBValueL')
    self.PSNameL.setObjectName('PSNameL')
    self.PSValueL.setObjectName('PSValueL')
    self.ProfitabilitySubTitleL.setObjectName('ProfitabilitySubTitleL')
    self.ROENameL.setObjectName('ROENameL')
    self.ROEValueL.setObjectName('ROEValueL')
    self.ROANameL.setObjectName('ROANameL')
    self.ROAValueL.setObjectName('ROAValueL')
    self.ROINameL.setObjectName('ROINameL')
    self.ROIValueL.setObjectName('ROIValueL')
    self.NetMarginNameL.setObjectName('NetMarginNameL')
    self.NetMarginValueL.setObjectName('NetMarginValueL')
    self.OperatingMarginNameL.setObjectName('OperatingMarginNameL')
    self.OperatingMarginValueL.setObjectName('OperatingMarginValueL')
    self.GrossMarginNameL.setObjectName('GrossMarginNameL')
    self.GrossMarginValueL.setObjectName('GrossMarginValueL')
    self.BalanceSubTitleL.setObjectName('BalanceSubTitleL')
    self.AssetsNameL.setObjectName('AssetsNameL')
    self.AssetsValueL.setObjectName('AssetsValueL')
    self.LiabilitiesNameL.setObjectName('LiabilitiesNameL')
    self.LiabilitiesValueL.setObjectName('LiabilitiesValueL')
    self.EquityNameL.setObjectName('EquityNameL')
    self.EquityValueL.setObjectName('EquityValueL')
    self.CashNameL.setObjectName('CashNameL')
    self.CashValueL.setObjectName('CashValueL')
    self.DebtNameL.setObjectName('DebtNameL')
    self.DebtValueL.setObjectName('DebtValueL')
    self.FinancialReportsTitleL.setObjectName('FinancialReportsTitleL')
    self.IncomeStatementSubTitleL.setObjectName('IncomeStatementSubTitleL')
    self.RevenueNameL.setObjectName('RevenueNameL')
    self.RevenueValueL.setObjectName('RevenueValueL')
    self.GrossProfitNameL.setObjectName('GrossProfitNameL')
    self.GrossProfitValueL.setObjectName('GrossProfitValueL')
    self.OperatingIncomeNameL.setObjectName('OperatingIncomeNameL')
    self.OperatingIncomeValueL.setObjectName('OperatingIncomeValueL')
    self.NetIncomeNameL.setObjectName('NetIncomeNameL')
    self.NetIncomeValueL.setObjectName('NetIncomeValueL')
    self.EPSIncomeNameL.setObjectName('EPSIncomeNameL')
    self.EPSIncomeValueL.setObjectName('EPSIncomeValueL')
    self.BalanceSheetSubTitleL.setObjectName('BalanceSheetSubTitleL')
    self.TotalAssetsNameL.setObjectName('TotalAssetsNameL')
    self.TotalAssetsValueL.setObjectName('TotalAssetsValueL')
    self.TotalLiabilitiesNameL.setObjectName('TotalLiabilitiesNameL')
    self.TotalLiabilitiesValueL.setObjectName('TotalLiabilitiesValueL')
    self.ShareholderEqulityNameL.setObjectName('ShareholderEqulityNameL')
    self.ShareholderEqulityValueL.setObjectName('ShareholderEqulityValueL')
    self.CashFlowSubTitleL.setObjectName('CashFlowSubTitleL')
    self.OperatingCashFlowNameL.setObjectName('OperatingCashFlowNameL')
    self.OperatingCashFlowValueL.setObjectName('OperatingCashFlowValueL')
    self.InvestingCashFlowNameL.setObjectName('InvestingCashFlowNameL')
    self.InvestingCashFlowValueL.setObjectName('InvestingCashFlowValueL')
    self.FinancingCashFlowNameL.setObjectName('FinancingCashFlowNameL')
    self.FinancingCashFlowValueL.setObjectName('FinancingCashFlowValueL')
    self.FreeCashFlowNameL.setObjectName('FreeCashFlowNameL')
    self.FreeCashFlowValueL.setObjectName('FreeCashFlowValueL')
    self.DividendDataSubTitleL.setObjectName('DividendDataSubTitleL')
    self.DividendYieldNameL.setObjectName('DividendYieldNameL')
    self.DividendYieldValueL.setObjectName('DividendYieldValueL')
    self.DividendPerShareNameL.setObjectName('DividendPerShareNameL')
    self.DividendPerShareValueL.setObjectName('DividendPerShareValueL')
    self.PayoutRatioNameL.setObjectName('PayoutRatioNameL')
    self.PayoutRatioValueL.setObjectName('PayoutRatioValueL')
    self.DividendHistoryNameL.setObjectName('DividendHistoryNameL')
    self.DividendHistoryValueL.setObjectName('DividendHistoryValueL')
    self.ExDividendNameL.setObjectName('ExDividendNameL')
    self.ExDividendValueL.setObjectName('ExDividendValueL')
    self.PaymentDateNameL.setObjectName('PaymentDateNameL')
    self.PaymentDateValueL.setObjectName('PaymentDateValueL')
    self.CorporationDataTitleL.setObjectName('CorporationDataTitleL')
    self.CorporateActionsSubTitleL.setObjectName('CorporateActionsSubTitleL')
    self.StockSplitNameL.setObjectName('StockSplitNameL')
    self.StockSplitValueL.setObjectName('StockSplitValueL')
    self.ReverseSplitNameL.setObjectName('ReverseSplitNameL')
    self.ReverseSplitValueL.setObjectName('ReverseSplitValueL')
    self.MergersNameL.setObjectName('MergersNameL')
    self.MergersValueL.setObjectName('MergersValueL')
    self.AcquisitionsNameL.setObjectName('AcquisitionsNameL')
    self.AcquisitionsValueL.setObjectName('AcquisitionsValueL')

    self.BuyBacksNameL.setObjectName('BuyBacksNameL')
    self.BuyBacksValueL.setObjectName('BuyBacksValueL')
    self.EventsSubTitleL.setObjectName('EventsSubTitleL')
    self.EarningsDateNameL.setObjectName('EarningsDateNameL')
    self.EarningsDateValueL.setObjectName('EarningsDateValueL')
    self.AGMNameL.setObjectName('AGMNameL')
    self.AGMValueL.setObjectName('AGMValueL')
    self.InvestorDayNameL.setObjectName('InvestorDayNameL')
    self.InvestorDayValueL.setObjectName('InvestorDayValueL')
    self.OwnershipDataTitleL.setObjectName('OwnershipDataTitleL')
    self.ShareholdingSubTitleL.setObjectName('ShareholdingSubTitleL')
    self.InstitutionalOwnershipNameL.setObjectName('InstitutionalOwnershipNameL')
    self.InstitutionalOwnershipValueL.setObjectName('InstitutionalOwnershipValueL')
    self.InsiderOwnershipNameL.setObjectName('InsiderOwnershipNameL')
    self.InsiderOwnershipValueL.setObjectName('InsiderOwnershipValueL')
    self.TopShareholdersNameL.setObjectName('TopShareholdersNameL')
    self.TopShareholdersValueL.setObjectName('TopShareholdersValueL')
    self.InsiderTradingSubTitleL.setObjectName('InsiderTradingSubTitleL')
    self.InsiderBuysNameL.setObjectName('InsiderBuysNameL')
    self.InsiderBuysValueL.setObjectName('InsiderBuysValueL')
    self.InsiderSellsNameL.setObjectName('InsiderSellsNameL')
    self.InsiderSellsValueL.setObjectName('InsiderSellsValueL')
    self.AnaliticalDataTitleL.setObjectName('AnaliticalDataTitleL')
    self.MovingAveragesNameL.setObjectName('MovingAveragesNameL')
    self.MovingAveragesValueL.setObjectName('MovingAveragesValueL')
    self.RSINameL.setObjectName('RSINameL')
    self.RSIValueL.setObjectName('RSIValueL')
    self.MACDNameL.setObjectName('MACDNameL')
    self.MACDValueL.setObjectName('MACDValueL')
    self.BollingerBandsNameL.setObjectName('BollingerBandsNameL')
    self.BollingerBandsValueL.setObjectName('BollingerBandsValueL')
    self.MomentumNameL.setObjectName('MomentumNameL')
    self.MomentumValueL.setObjectName('MomentumValueL')
    self.VolatillityNameL.setObjectName('VolatillityNameL')
    self.VolatillityValueL.setObjectName('VolatillityValueL')
    self.ESGDataTitleL.setObjectName('ESGDataTitleL')
    self.ESGScoreNameL.setObjectName('ESGScoreNameL')
    self.ESGScoreValueL.setObjectName('ESGScoreValueL')
    self.EnvironmentalScoreNameL.setObjectName('EnvironmentalScoreNameL')
    self.EnvironmentalScoreValueL.setObjectName('EnvironmentalScoreValueL')
    self.GovernanceScoreNameL.setObjectName('GovernanceScoreNameL')
    self.GovernanceScoreValueL.setObjectName('GovernanceScoreValueL')
    self.FundamentalDataTitleL.setProperty('class', 'Title')
    self.FinancialReportsTitleL.setProperty('class', 'Title')
    self.CorporationDataTitleL.setProperty('class', 'Title')
    self.EventsSubTitleL.setProperty('class', 'Title')
    self.OwnershipDataTitleL.setProperty('class', 'Title')
    self.AnaliticalDataTitleL.setProperty('class', 'Title')
    self.ESGDataTitleL.setProperty('class', 'Title')
    self.IndicatorsSubTitleL.setProperty('class', 'SubTitle')
    self.ProfitabilitySubTitleL.setProperty('class', 'SubTitle')
    self.BalanceSubTitleL.setProperty('class', 'SubTitle')
    self.IncomeStatementSubTitleL.setProperty('class', 'SubTitle')
    self.BalanceSheetSubTitleL.setProperty('class', 'SubTitle')
    self.CashFlowSubTitleL.setProperty('class', 'SubTitle')
    self.DividendDataSubTitleL.setProperty('class', 'SubTitle')
    self.CorporateActionsSubTitleL.setProperty('class', 'SubTitle')
    self.ShareholdingSubTitleL.setProperty('class', 'SubTitle')
    self.InsiderTradingSubTitleL.setProperty('class', 'SubTitle')
    self.MarketCapNameL.setProperty('class', 'Name')
    self.PENameL.setProperty('class', 'Name')
    self.ForwardPENameL.setProperty('class', 'Name')
    self.PEGNameL.setProperty('class', 'Name')
    self.PBNameL.setProperty('class', 'Name')
    self.PSNameL.setProperty('class', 'Name')
    self.ROENameL.setProperty('class', 'Name')
    self.ROANameL.setProperty('class', 'Name')
    self.ROINameL.setProperty('class', 'Name')
    self.NetMarginNameL.setProperty('class', 'Name')
    self.OperatingMarginNameL.setProperty('class', 'Name')
    self.GrossMarginNameL.setProperty('class', 'Name')
    self.AssetsNameL.setProperty('class', 'Name')
    self.LiabilitiesNameL.setProperty('class', 'Name')
    self.EquityNameL.setProperty('class', 'Name')
    self.CashNameL.setProperty('class', 'Name')
    self.DebtNameL.setProperty('class', 'Name')
    self.RevenueNameL.setProperty('class', 'Name')
    self.GrossProfitNameL.setProperty('class', 'Name')
    self.OperatingIncomeNameL.setProperty('class', 'Name')
    self.NetIncomeNameL.setProperty('class', 'Name')
    self.EPSIncomeNameL.setProperty('class', 'Name')
    self.TotalAssetsNameL.setProperty('class', 'Name')
    self.TotalLiabilitiesNameL.setProperty('class', 'Name')
    self.ShareholderEqulityNameL.setProperty('class', 'Name')
    self.OperatingCashFlowNameL.setProperty('class', 'Name')
    self.InvestingCashFlowNameL.setProperty('class', 'Name')
    self.FinancingCashFlowNameL.setProperty('class', 'Name')
    self.FreeCashFlowNameL.setProperty('class', 'Name')
    self.DividendYieldNameL.setProperty('class', 'Name')
    self.DividendPerShareNameL.setProperty('class', 'Name')
    self.PayoutRatioNameL.setProperty('class', 'Name')
    self.DividendHistoryNameL.setProperty('class', 'Name')
    self.ExDividendNameL.setProperty('class', 'Name')
    self.PaymentDateNameL.setProperty('class', 'Name')
    self.StockSplitNameL.setProperty('class', 'Name')
    self.ReverseSplitNameL.setProperty('class', 'Name')
    self.MergersNameL.setProperty('class', 'Name')
    self.AcquisitionsNameL.setProperty('class', 'Name')
    self.BuyBacksNameL.setProperty('class', 'Name')
    self.EarningsDateNameL.setProperty('class', 'Name')
    self.AGMNameL.setProperty('class', 'Name')
    self.InvestorDayNameL.setProperty('class', 'Name')
    self.InstitutionalOwnershipNameL.setProperty('class', 'Name')
    self.InsiderOwnershipNameL.setProperty('class', 'Name')
    self.TopShareholdersNameL.setProperty('class', 'Name')
    self.InsiderBuysNameL.setProperty('class', 'Name')
    self.InsiderSellsNameL.setProperty('class', 'Name')
    self.MovingAveragesNameL.setProperty('class', 'Name')
    self.RSINameL.setProperty('class', 'Name')
    self.MACDNameL.setProperty('class', 'Name')
    self.BollingerBandsNameL.setProperty('class', 'Name')
    self.MomentumNameL.setProperty('class', 'Name')
    self.VolatillityNameL.setProperty('class', 'Name')
    self.ESGScoreNameL.setProperty('class', 'Name')
    self.EnvironmentalScoreNameL.setProperty('class', 'Name')
    self.GovernanceScoreNameL.setProperty('class', 'Name')
    self.MarketCapValueL.setProperty('class', 'Value')
    self.PEValueL.setProperty('class', 'Value')
    self.ForwardPEValueL.setProperty('class', 'Value')
    self.PEGValueL.setProperty('class', 'Value')
    self.PBValueL.setProperty('class', 'Value')
    self.PSValueL.setProperty('class', 'Value')
    self.ROEValueL.setProperty('class', 'Value')
    self.ROAValueL.setProperty('class', 'Value')
    self.ROIValueL.setProperty('class', 'Value')
    self.NetMarginValueL.setProperty('class', 'Value')
    self.OperatingMarginValueL.setProperty('class', 'Value')
    self.GrossMarginValueL.setProperty('class', 'Value')
    self.AssetsValueL.setProperty('class', 'Value')
    self.LiabilitiesValueL.setProperty('class', 'Value')
    self.EquityValueL.setProperty('class', 'Value')
    self.CashValueL.setProperty('class', 'Value')
    self.DebtValueL.setProperty('class', 'Value')
    self.RevenueValueL.setProperty('class', 'Value')
    self.GrossProfitValueL.setProperty('class', 'Value')
    self.OperatingIncomeValueL.setProperty('class', 'Value')
    self.NetIncomeValueL.setProperty('class', 'Value')
    self.EPSIncomeValueL.setProperty('class', 'Value')
    self.TotalAssetsValueL.setProperty('class', 'Value')
    self.TotalLiabilitiesValueL.setProperty('class', 'Value')
    self.ShareholderEqulityValueL.setProperty('class', 'Value')
    self.OperatingCashFlowValueL.setProperty('class', 'Value')
    self.InvestingCashFlowValueL.setProperty('class', 'Value')
    self.FinancingCashFlowValueL.setProperty('class', 'Value')
    self.FreeCashFlowValueL.setProperty('class', 'Value')
    self.DividendYieldValueL.setProperty('class', 'Value')
    self.DividendPerShareValueL.setProperty('class', 'Value')
    self.PayoutRatioValueL.setProperty('class', 'Value')
    self.DividendHistoryValueL.setProperty('class', 'Value')
    self.ExDividendValueL.setProperty('class', 'Value')
    self.PaymentDateValueL.setProperty('class', 'Value')
    self.StockSplitValueL.setProperty('class', 'Value')
    self.ReverseSplitValueL.setProperty('class', 'Value')
    self.MergersValueL.setProperty('class', 'Value')
    self.AcquisitionsValueL.setProperty('class', 'Value')
    self.BuyBacksValueL.setProperty('class', 'Value')
    self.EarningsDateValueL.setProperty('class', 'Value')
    self.AGMValueL.setProperty('class', 'Value')
    self.InvestorDayValueL.setProperty('class', 'Value')
    self.InstitutionalOwnershipValueL.setProperty('class', 'Value')
    self.InsiderOwnershipValueL.setProperty('class', 'Value')
    self.TopShareholdersValueL.setProperty('class', 'Value')
    self.InsiderBuysValueL.setProperty('class', 'Value')
    self.InsiderSellsValueL.setProperty('class', 'Value')
    self.MovingAveragesValueL.setProperty('class', 'Value')
    self.RSIValueL.setProperty('class', 'Value')
    self.MACDValueL.setProperty('class', 'Value')
    self.BollingerBandsValueL.setProperty('class', 'Value')
    self.MomentumValueL.setProperty('class', 'Value')
    self.VolatillityValueL.setProperty('class', 'Value')
    self.ESGScoreValueL.setProperty('class', 'Value')
    self.EnvironmentalScoreValueL.setProperty('class', 'Value')
    self.GovernanceScoreValueL.setProperty('class', 'Value')

    self.LayoutL.addWidget(self.FundamentalDataTitleL, 0, 0, 1, 100)

    self.LayoutL.addWidget(self.IndicatorsSubTitleL, 1, 0, 1, 50)
    self.LayoutL.addWidget(self.MarketCapNameL, 2, 0, 1, 25)
    self.LayoutL.addWidget(self.MarketCapValueL, 2, 25, 1, 25)
    self.LayoutL.addWidget(self.PENameL, 3, 0, 1, 25)
    self.LayoutL.addWidget(self.PEValueL, 3, 25, 1, 25)
    self.LayoutL.addWidget(self.ForwardPENameL, 4, 0, 1, 25)
    self.LayoutL.addWidget(self.ForwardPEValueL, 4, 25, 1, 25)
    self.LayoutL.addWidget(self.PEGNameL, 5, 0, 1, 25)
    self.LayoutL.addWidget(self.PEGValueL, 5, 25, 1, 25)
    self.LayoutL.addWidget(self.PBNameL, 6, 0, 1, 25)
    self.LayoutL.addWidget(self.PBValueL, 6, 25, 1, 25)
    self.LayoutL.addWidget(self.PSNameL, 7, 0, 1, 25)
    self.LayoutL.addWidget(self.PSValueL, 7, 25, 1, 25)

    self.LayoutL.addWidget(self.ProfitabilitySubTitleL, 1, 50, 1, 50)
    self.LayoutL.addWidget(self.ROENameL, 2, 50, 1, 25)
    self.LayoutL.addWidget(self.ROEValueL, 2, 75, 1, 25)
    self.LayoutL.addWidget(self.ROANameL, 3, 50, 1, 25)
    self.LayoutL.addWidget(self.ROAValueL, 3, 75, 1, 25)
    self.LayoutL.addWidget(self.ROINameL, 4, 50, 1, 25)
    self.LayoutL.addWidget(self.ROIValueL, 4, 75, 1, 25)
    self.LayoutL.addWidget(self.NetMarginNameL, 5, 50, 1, 25)
    self.LayoutL.addWidget(self.NetMarginValueL, 5, 75, 1, 25)
    self.LayoutL.addWidget(self.OperatingMarginNameL, 6, 50, 1, 25)
    self.LayoutL.addWidget(self.OperatingMarginValueL, 6, 75, 1, 25)
    self.LayoutL.addWidget(self.GrossMarginNameL, 7, 50 ,1, 25)
    self.LayoutL.addWidget(self.GrossMarginValueL, 7, 75, 1, 25)

    self.LayoutL.addWidget(self.BalanceSubTitleL, 8, 0, 1, 50)
    self.LayoutL.addWidget(self.AssetsNameL, 9, 0, 1, 25)
    self.LayoutL.addWidget(self.AssetsValueL, 9, 25, 1, 25)
    self.LayoutL.addWidget(self.LiabilitiesNameL, 10, 0, 1, 25)
    self.LayoutL.addWidget(self.LiabilitiesValueL, 10, 25, 1, 25)
    self.LayoutL.addWidget(self.EquityNameL, 11, 0, 1, 25)
    self.LayoutL.addWidget(self.EquityValueL, 11, 25, 1, 25)
    self.LayoutL.addWidget(self.CashNameL, 12, 0, 1, 25)
    self.LayoutL.addWidget(self.CashValueL, 12, 25, 1, 25)
    self.LayoutL.addWidget(self.DebtNameL, 13, 0, 1, 25)
    self.LayoutL.addWidget(self.DebtValueL, 13, 25, 1, 25)

    self.LayoutL.addWidget(self.FinancialReportsTitleL, 14, 0, 1, 100)

    self.LayoutL.addWidget(self.IncomeStatementSubTitleL, 15, 0, 1, 50)
    self.LayoutL.addWidget(self.RevenueNameL, 16, 0, 1, 25)
    self.LayoutL.addWidget(self.RevenueValueL, 16, 25, 1, 25)
    self.LayoutL.addWidget(self.GrossProfitNameL, 17, 0, 1, 25)
    self.LayoutL.addWidget(self.GrossProfitValueL, 17, 25, 1, 25)
    self.LayoutL.addWidget(self.OperatingIncomeNameL, 18, 0, 1, 25)
    self.LayoutL.addWidget(self.OperatingIncomeValueL, 18, 25, 1, 25)
    self.LayoutL.addWidget(self.NetIncomeNameL, 19, 0, 1, 25)
    self.LayoutL.addWidget(self.NetIncomeValueL, 19, 25, 1, 25)
    self.LayoutL.addWidget(self.EPSIncomeNameL, 20, 0, 1, 25)
    self.LayoutL.addWidget(self.EPSIncomeValueL, 20, 25, 1, 25)

    self.LayoutL.addWidget(self.BalanceSheetSubTitleL, 21, 50, 1, 50)
    self.LayoutL.addWidget(self.TotalAssetsNameL, 22, 50, 1, 25)
    self.LayoutL.addWidget(self.TotalAssetsValueL, 22, 75, 1, 25)
    self.LayoutL.addWidget(self.TotalLiabilitiesNameL, 23, 50, 1, 25)
    self.LayoutL.addWidget(self.TotalLiabilitiesValueL, 23, 75, 1, 25)
    self.LayoutL.addWidget(self.ShareholderEqulityNameL, 24, 50, 1, 25)
    self.LayoutL.addWidget(self.ShareholderEqulityValueL, 24, 75, 1, 25)

    self.LayoutL.addWidget(self.CashFlowSubTitleL, 25, 0, 1, 50)
    self.LayoutL.addWidget(self.OperatingCashFlowNameL, 26, 0, 1, 25)
    self.LayoutL.addWidget(self.OperatingCashFlowValueL, 26, 25, 1, 25)
    self.LayoutL.addWidget(self.InvestingCashFlowNameL, 27, 0, 1, 25)
    self.LayoutL.addWidget(self.InvestingCashFlowValueL, 27, 25, 1, 25)
    self.LayoutL.addWidget(self.FinancingCashFlowNameL, 28, 0, 1, 25)
    self.LayoutL.addWidget(self.FinancingCashFlowValueL, 28, 25, 1, 25)
    self.LayoutL.addWidget(self.FreeCashFlowNameL, 29, 0, 1, 25)
    self.LayoutL.addWidget(self.FreeCashFlowValueL, 29, 25, 1, 25)

    self.LayoutL.addWidget(self.DividendDataSubTitleL, 30, 50, 1, 50)
    self.LayoutL.addWidget(self.DividendYieldNameL, 31, 50, 1, 25)
    self.LayoutL.addWidget(self.DividendYieldValueL, 31, 75, 1, 25)
    self.LayoutL.addWidget(self.DividendPerShareNameL, 32, 50, 1, 25)
    self.LayoutL.addWidget(self.DividendPerShareValueL, 32, 75, 1, 25)
    self.LayoutL.addWidget(self.PayoutRatioNameL, 33, 50, 1, 25)
    self.LayoutL.addWidget(self.PayoutRatioValueL, 33, 75, 1, 25)
    self.LayoutL.addWidget(self.DividendHistoryNameL, 34, 50, 1, 25)
    self.LayoutL.addWidget(self.DividendHistoryValueL, 34, 75, 1, 25)
    self.LayoutL.addWidget(self.ExDividendNameL, 35, 50, 1, 25)
    self.LayoutL.addWidget(self.ExDividendValueL, 35, 75, 1, 25)
    self.LayoutL.addWidget(self.PaymentDateNameL, 36, 50, 1, 25)
    self.LayoutL.addWidget(self.PaymentDateValueL, 36, 75, 1, 25)

    self.LayoutL.addWidget(self.CorporationDataTitleL, 37, 0, 1, 100)

    self.LayoutL.addWidget(self.CorporateActionsSubTitleL, 38, 0, 1, 50)
    self.LayoutL.addWidget(self.StockSplitNameL, 39, 0, 1, 25)
    self.LayoutL.addWidget(self.StockSplitValueL, 39, 25, 1, 25)
    self.LayoutL.addWidget(self.ReverseSplitNameL, 40, 0, 1, 25)
    self.LayoutL.addWidget(self.ReverseSplitValueL, 40, 25, 1, 25)
    self.LayoutL.addWidget(self.MergersNameL, 41, 0, 1, 25)
    self.LayoutL.addWidget(self.MergersValueL, 41, 25, 1, 25)
    self.LayoutL.addWidget(self.AcquisitionsNameL, 42, 0, 1, 25)
    self.LayoutL.addWidget(self.AcquisitionsValueL, 42, 25, 1, 25)
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )
    self.LayoutL.addWidget(self. , , , , )


    self.LayoutL.setSpacing(0)
    self.LayoutL.setContentsMargins(0,0,0,0)
    for i in range(100):
        self.LayoutL.setColumnStretch(i, 1)
    self.WidgetW.setLayout(self.LayoutL)
    self.MainLayoutL.addWidget(self.TitleL, 0, 0, 10, 100)
    self.MainLayoutL.addWidget(self.ScrollS, 10, 0, 90, 100)
    self.MainLayoutL.setSpacing(0)
    self.MainLayoutL.setContentsMargins(0,0,0,0)
    for i in range(100):
        self.MainLayoutL.setRowStretch(i, 1)
        self.MainLayoutL.setColumnStretch(i, 1)
    self.setLayout(self.MainLayoutL)
    self.show()
    self.ScrollS.setWidget(self.WidgetW)
    self.ScrollS.setWidgetResizable(True)

    self.TitleL.setAlignment(Qt.AlignCenter)

    self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

def StockReloadStyle(self):
    t = self.Theme
    m = open(f'{self.Path}/APP_FILES/PYTHON/ObjectStats/BMain.css').read()
    c = open(f'{self.Path}/APP_FILES/PYTHON/ObjectStats/B{t}.css').read()
    self.setStyleSheet(m+c)

def StockRetranslate(self):
    t = json.load(open(f'{self.Path}/APP_FILES/PYTHON/ObjectStats/CStockTranslate.json', 'r'))
    l = self.Language
    self.TitleL.setText(t['TitleL'][l])
    