#   --- Improt ---
import json
from PyQt5.QtWidgets import (
    QSizePolicy
)
from PyQt5.QtCore import (
    Qt,
    QSize
)
from PyQt5.QtGui import (
    QPixmap,
    QIcon,
    QPainter
)
from PyQt5.QtSvg import (
    QSvgRenderer
)

def StockUi(self):
    self.setObjectName('ObjectStatsS')
    self.WidgetW.setObjectName('WidgetW')
    self.FundamentalDataTitleL.setObjectName('FundamentalDataTitleL')
    self.IndicatorsSubTitleL.setObjectName('IndicatorsSubTitleL')
    self.MarketCapNameL.setObjectName('MarketCapNameL')
    self.MarketCapValueL.setObjectName('MarketCapValueL')
    self.PENameL.setObjectName('PENameL')
    self.PEValueL.setObjectName('PEValueL')
    self.ForwardPENameL.setObjectName('ForwardPENameL')
    self.ForwardPEValueL.setObjectName('ForwardPEValueL')
    self.PEGNameL.setObjectName('PEGNameL')
    self.PEGValueL.setObjectName('PEGValueL')
    self.PBNameL.setObjectName('PBNameL')
    self.PBValueL.setObjectName('PBValueL')
    self.PSNameL.setObjectName('PSNameL')
    self.PSValueL.setObjectName('PSValueL')
    self.ProfitabilitySubTitleL.setObjectName('ProfitabilitySubTitleL')
    self.ROENameL.setObjectName('ROENameL')
    self.ROEValueL.setObjectName('ROEValueL')
    self.ROANameL.setObjectName('ROANameL')
    self.ROAValueL.setObjectName('ROAValueL')
    self.ROINameL.setObjectName('ROINameL')
    self.ROIValueL.setObjectName('ROIValueL')
    self.NetMarginNameL.setObjectName('NetMarginNameL')
    self.NetMarginValueL.setObjectName('NetMarginValueL')
    self.OperatingMarginNameL.setObjectName('OperatingMarginNameL')
    self.OperatingMarginValueL.setObjectName('OperatingMarginValueL')
    self.GrossMarginNameL.setObjectName('GrossMarginNameL')
    self.GrossMarginValueL.setObjectName('GrossMarginValueL')
    self.BalanceSubTitleL.setObjectName('BalanceSubTitleL')
    self.AssetsNameL.setObjectName('AssetsNameL')
    self.AssetsValueL.setObjectName('AssetsValueL')
    self.LiabilitiesNameL.setObjectName('LiabilitiesNameL')
    self.LiabilitiesValueL.setObjectName('LiabilitiesValueL')
    self.EquityNameL.setObjectName('EquityNameL')
    self.EquityValueL.setObjectName('EquityValueL')
    self.CashNameL.setObjectName('CashNameL')
    self.CashValueL.setObjectName('CashValueL')
    self.DebtNameL.setObjectName('DebtNameL')
    self.DebtValueL.setObjectName('DebtValueL')
    self.FinancialReportsTitleL.setObjectName('FinancialReportsTitleL')
    self.IncomeStatementSubTitleL.setObjectName('IncomeStatementSubTitleL')
    self.RevenueNameL.setObjectName('RevenueNameL')
    self.RevenueValueL.setObjectName('RevenueValueL')
    self.GrossProfitNameL.setObjectName('GrossProfitNameL')
    self.GrossProfitValueL.setObjectName('GrossProfitValueL')
    self.OperatingIncomeNameL.setObjectName('OperatingIncomeNameL')
    self.OperatingIncomeValueL.setObjectName('OperatingIncomeValueL')
    self.NetIncomeNameL.setObjectName('NetIncomeNameL')
    self.NetIncomeValueL.setObjectName('NetIncomeValueL')
    self.EPSIncomeNameL.setObjectName('EPSIncomeNameL')
    self.EPSIncomeValueL.setObjectName('EPSIncomeValueL')
    self.BalanceSheetSubTitleL.setObjectName('BalanceSheetSubTitleL')
    self.TotalAssetsNameL.setObjectName('TotalAssetsNameL')
    self.TotalAssetsValueL.setObjectName('TotalAssetsValueL')
    self.TotalLiabilitiesNameL.setObjectName('TotalLiabilitiesNameL')
    self.TotalLiabilitiesValueL.setObjectName('TotalLiabilitiesValueL')
    self.ShareholderEqulityNameL.setObjectName('ShareholderEqulityNameL')
    self.ShareholderEqulityValueL.setObjectName('ShareholderEqulityValueL')
    self.CashFlowSubTitleL.setObjectName('CashFlowSubTitleL')
    self.OperatingCashFlowNameL.setObjectName('OperatingCashFlowNameL')
    self.OperatingCashFlowValueL.setObjectName('OperatingCashFlowValueL')
    self.InvestingCashFlowNameL.setObjectName('InvestingCashFlowNameL')
    self.InvestingCashFlowValueL.setObjectName('InvestingCashFlowValueL')
    self.FinancingCashFlowNameL.setObjectName('FinancingCashFlowNameL')
    self.FinancingCashFlowValueL.setObjectName('FinancingCashFlowValueL')
    self.FreeCashFlowNameL.setObjectName('FreeCashFlowNameL')
    self.FreeCashFlowValueL.setObjectName('FreeCashFlowValueL')
    self.DividendDataSubTitleL.setObjectName('DividendDataSubTitleL')
    self.DividendYieldNameL.setObjectName('DividendYieldNameL')
    self.DividendYieldValueL.setObjectName('DividendYieldValueL')
    self.DividendPerShareNameL.setObjectName('DividendPerShareNameL')
    self.DividendPerShareValueL.setObjectName('DividendPerShareValueL')
    self.PayoutRatioNameL.setObjectName('PayoutRatioNameL')
    self.PayoutRatioValueL.setObjectName('PayoutRatioValueL')
    self.DividendHistoryNameL.setObjectName('DividendHistoryNameL')
    self.DividendHistoryValueL.setObjectName('DividendHistoryValueL')
    self.ExDividendNameL.setObjectName('ExDividendNameL')
    self.ExDividendValueL.setObjectName('ExDividendValueL')
    self.PaymentDateNameL.setObjectName('PaymentDateNameL')
    self.PaymentDateValueL.setObjectName('PaymentDateValueL')
    self.CorporationDataTitleL.setObjectName('CorporationDataTitleL')
    self.CorporateActionsSubTitleL.setObjectName('CorporateActionsSubTitleL')
    self.StockSplitNameL.setObjectName('StockSplitNameL')
    self.StockSplitValueL.setObjectName('StockSplitValueL')
    self.ReverseSplitNameL.setObjectName('ReverseSplitNameL')
    self.ReverseSplitValueL.setObjectName('ReverseSplitValueL')
    self.MergersNameL.setObjectName('MergersNameL')
    self.MergersValueL.setObjectName('MergersValueL')
    self.AcquisitionsNameL.setObjectName('AcquisitionsNameL')
    self.AcquisitionsValueL.setObjectName('AcquisitionsValueL')
    self.BuyBacksNameL.setObjectName('BuyBacksNameL')
    self.BuyBacksValueL.setObjectName('BuyBacksValueL')
    self.EventsSubTitleL.setObjectName('EventsSubTitleL')
    self.EarningsDateNameL.setObjectName('EarningsDateNameL')
    self.EarningsDateValueL.setObjectName('EarningsDateValueL')
    self.AGMNameL.setObjectName('AGMNameL')
    self.AGMValueL.setObjectName('AGMValueL')
    self.InvestorDayNameL.setObjectName('InvestorDayNameL')
    self.InvestorDayValueL.setObjectName('InvestorDayValueL')
    self.OwnershipDataTitleL.setObjectName('OwnershipDataTitleL')
    self.ShareholdingSubTitleL.setObjectName('ShareholdingSubTitleL')
    self.InstitutionalOwnershipNameL.setObjectName('InstitutionalOwnershipNameL')
    self.InstitutionalOwnershipValueL.setObjectName('InstitutionalOwnershipValueL')
    self.InsiderOwnershipNameL.setObjectName('InsiderOwnershipNameL')
    self.InsiderOwnershipValueL.setObjectName('InsiderOwnershipValueL')
    self.TopShareholdersNameL.setObjectName('TopShareholdersNameL')
    self.TopShareholdersValueL.setObjectName('TopShareholdersValueL')
    self.InsiderTradingSubTitleL.setObjectName('InsiderTradingSubTitleL')
    self.InsiderBuysNameL.setObjectName('InsiderBuysNameL')
    self.InsiderBuysValueL.setObjectName('InsiderBuysValueL')
    self.InsiderSellsNameL.setObjectName('InsiderSellsNameL')
    self.InsiderSellsValueL.setObjectName('InsiderSellsValueL')
    self.AnaliticalDataTitleL.setObjectName('AnaliticalDataTitleL')
    self.MovingAveragesNameL.setObjectName('MovingAveragesNameL')
    self.MovingAveragesValueL.setObjectName('MovingAveragesValueL')
    self.RSINameL.setObjectName('RSINameL')
    self.RSIValueL.setObjectName('RSIValueL')
    self.MACDNameL.setObjectName('MACDNameL')
    self.MACDValueL.setObjectName('MACDValueL')
    self.BollingerBandsNameL.setObjectName('BollingerBandsNameL')
    self.BollingerBandsValueL.setObjectName('BollingerBandsValueL')
    self.MomentumNameL.setObjectName('MomentumNameL')
    self.MomentumValueL.setObjectName('MomentumValueL')
    self.VolatillityNameL.setObjectName('VolatillityNameL')
    self.VolatillityValueL.setObjectName('VolatillityValueL')
    self.ESGDataTitleL.setObjectName('ESGDataTitleL')
    self.ESGScoreNameL.setObjectName('ESGScoreNameL')
    self.ESGScoreValueL.setObjectName('ESGScoreValueL')
    self.EnvironmentalScoreNameL.setObjectName('EnvironmentalScoreNameL')
    self.EnvironmentalScoreValueL.setObjectName('EnvironmentalScoreValueL')
    self.GovernanceScoreNameL.setObjectName('GovernanceScoreNameL')
    self.GovernanceScoreValueL.setObjectName('GovernanceScoreValueL')
    self.FundamentalDataTitleL.setProperty('class', 'Title')
    self.FinancialReportsTitleL.setProperty('class', 'Title')
    self.CorporationDataTitleL.setProperty('class', 'Title')
    self.EventsSubTitleL.setProperty('class', 'Title')
    self.OwnershipDataTitleL.setProperty('class', 'Title')
    self.AnaliticalDataTitleL.setProperty('class', 'Title')
    self.ESGDataTitleL.setProperty('class', 'Title')
    self.IndicatorsSubTitleL.setProperty('class', 'SubTitle')
    self.ProfitabilitySubTitleL.setProperty('class', 'SubTitle')
    self.BalanceSubTitleL.setProperty('class', 'SubTitle')
    self.IncomeStatementSubTitleL.setProperty('class', 'SubTitle')
    self.BalanceSheetSubTitleL.setProperty('class', 'SubTitle')
    self.CashFlowSubTitleL.setProperty('class', 'SubTitle')
    self.DividendDataSubTitleL.setProperty('class', 'SubTitle')
    self.CorporateActionsSubTitleL.setProperty('class', 'SubTitle')
    self.ShareholdingSubTitleL.setProperty('class', 'SubTitle')
    self.InsiderTradingSubTitleL.setProperty('class', 'SubTitle')
    self.MarketCapNameL.setProperty('class', 'Name')
    self.PENameL.setProperty('class', 'Name')
    self.ForwardPENameL.setProperty('class', 'Name')
    self.PEGNameL.setProperty('class', 'Name')
    self.PBNameL.setProperty('class', 'Name')
    self.PSNameL.setProperty('class', 'Name')
    self.ROENameL.setProperty('class', 'Name')
    self.ROANameL.setProperty('class', 'Name')
    self.ROINameL.setProperty('class', 'Name')
    self.NetMarginNameL.setProperty('class', 'Name')
    self.OperatingMarginNameL.setProperty('class', 'Name')
    self.GrossMarginNameL.setProperty('class', 'Name')
    self.AssetsNameL.setProperty('class', 'Name')
    self.LiabilitiesNameL.setProperty('class', 'Name')
    self.EquityNameL.setProperty('class', 'Name')
    self.CashNameL.setProperty('class', 'Name')
    self.DebtNameL.setProperty('class', 'Name')
    self.RevenueNameL.setProperty('class', 'Name')
    self.GrossProfitNameL.setProperty('class', 'Name')
    self.OperatingIncomeNameL.setProperty('class', 'Name')
    self.NetIncomeNameL.setProperty('class', 'Name')
    self.EPSIncomeNameL.setProperty('class', 'Name')
    self.TotalAssetsNameL.setProperty('class', 'Name')
    self.TotalLiabilitiesNameL.setProperty('class', 'Name')
    self.ShareholderEqulityNameL.setProperty('class', 'Name')
    self.OperatingCashFlowNameL.setProperty('class', 'Name')
    self.InvestingCashFlowNameL.setProperty('class', 'Name')
    self.FinancingCashFlowNameL.setProperty('class', 'Name')
    self.FreeCashFlowNameL.setProperty('class', 'Name')
    self.DividendYieldNameL.setProperty('class', 'Name')
    self.DividendPerShareNameL.setProperty('class', 'Name')
    self.PayoutRatioNameL.setProperty('class', 'Name')
    self.DividendHistoryNameL.setProperty('class', 'Name')
    self.ExDividendNameL.setProperty('class', 'Name')
    self.PaymentDateNameL.setProperty('class', 'Name')
    self.StockSplitNameL.setProperty('class', 'Name')
    self.ReverseSplitNameL.setProperty('class', 'Name')
    self.MergersNameL.setProperty('class', 'Name')
    self.AcquisitionsNameL.setProperty('class', 'Name')
    self.BuyBacksNameL.setProperty('class', 'Name')
    self.EarningsDateNameL.setProperty('class', 'Name')
    self.AGMNameL.setProperty('class', 'Name')
    self.InvestorDayNameL.setProperty('class', 'Name')
    self.InstitutionalOwnershipNameL.setProperty('class', 'Name')
    self.InsiderOwnershipNameL.setProperty('class', 'Name')
    self.TopShareholdersNameL.setProperty('class', 'Name')
    self.InsiderBuysNameL.setProperty('class', 'Name')
    self.InsiderSellsNameL.setProperty('class', 'Name')
    self.MovingAveragesNameL.setProperty('class', 'Name')
    self.RSINameL.setProperty('class', 'Name')
    self.MACDNameL.setProperty('class', 'Name')
    self.BollingerBandsNameL.setProperty('class', 'Name')
    self.MomentumNameL.setProperty('class', 'Name')
    self.VolatillityNameL.setProperty('class', 'Name')
    self.ESGScoreNameL.setProperty('class', 'Name')
    self.EnvironmentalScoreNameL.setProperty('class', 'Name')
    self.GovernanceScoreNameL.setProperty('class', 'Name')
    self.MarketCapValueL.setProperty('class', 'Value')
    self.PEValueL.setProperty('class', 'Value')
    self.ForwardPEValueL.setProperty('class', 'Value')
    self.PEGValueL.setProperty('class', 'Value')
    self.PBValueL.setProperty('class', 'Value')
    self.PSValueL.setProperty('class', 'Value')
    self.ROEValueL.setProperty('class', 'Value')
    self.ROAValueL.setProperty('class', 'Value')
    self.ROIValueL.setProperty('class', 'Value')
    self.NetMarginValueL.setProperty('class', 'Value')
    self.OperatingMarginValueL.setProperty('class', 'Value')
    self.GrossMarginValueL.setProperty('class', 'Value')
    self.AssetsValueL.setProperty('class', 'Value')
    self.LiabilitiesValueL.setProperty('class', 'Value')
    self.EquityValueL.setProperty('class', 'Value')
    self.CashValueL.setProperty('class', 'Value')
    self.DebtValueL.setProperty('class', 'Value')
    self.RevenueValueL.setProperty('class', 'Value')
    self.GrossProfitValueL.setProperty('class', 'Value')
    self.OperatingIncomeValueL.setProperty('class', 'Value')
    self.NetIncomeValueL.setProperty('class', 'Value')
    self.EPSIncomeValueL.setProperty('class', 'Value')
    self.TotalAssetsValueL.setProperty('class', 'Value')
    self.TotalLiabilitiesValueL.setProperty('class', 'Value')
    self.ShareholderEqulityValueL.setProperty('class', 'Value')
    self.OperatingCashFlowValueL.setProperty('class', 'Value')
    self.InvestingCashFlowValueL.setProperty('class', 'Value')
    self.FinancingCashFlowValueL.setProperty('class', 'Value')
    self.FreeCashFlowValueL.setProperty('class', 'Value')
    self.DividendYieldValueL.setProperty('class', 'Value')
    self.DividendPerShareValueL.setProperty('class', 'Value')
    self.PayoutRatioValueL.setProperty('class', 'Value')
    self.DividendHistoryValueL.setProperty('class', 'Value')
    self.ExDividendValueL.setProperty('class', 'Value')
    self.PaymentDateValueL.setProperty('class', 'Value')
    self.StockSplitValueL.setProperty('class', 'Value')
    self.ReverseSplitValueL.setProperty('class', 'Value')
    self.MergersValueL.setProperty('class', 'Value')
    self.AcquisitionsValueL.setProperty('class', 'Value')
    self.BuyBacksValueL.setProperty('class', 'Value')
    self.EarningsDateValueL.setProperty('class', 'Value')
    self.AGMValueL.setProperty('class', 'Value')
    self.InvestorDayValueL.setProperty('class', 'Value')
    self.InstitutionalOwnershipValueL.setProperty('class', 'Value')
    self.InsiderOwnershipValueL.setProperty('class', 'Value')
    self.TopShareholdersValueL.setProperty('class', 'Value')
    self.InsiderBuysValueL.setProperty('class', 'Value')
    self.InsiderSellsValueL.setProperty('class', 'Value')
    self.MovingAveragesValueL.setProperty('class', 'Value')
    self.RSIValueL.setProperty('class', 'Value')
    self.MACDValueL.setProperty('class', 'Value')
    self.BollingerBandsValueL.setProperty('class', 'Value')
    self.MomentumValueL.setProperty('class', 'Value')
    self.VolatillityValueL.setProperty('class', 'Value')
    self.ESGScoreValueL.setProperty('class', 'Value')
    self.EnvironmentalScoreValueL.setProperty('class', 'Value')
    self.GovernanceScoreValueL.setProperty('class', 'Value')
    self.LayoutL.addWidget(self.FundamentalDataTitleL, 0, 0, 1, 100)
    self.LayoutL.addWidget(self.IndicatorsSubTitleL, 1, 0, 1, 50)
    self.LayoutL.addWidget(self.MarketCapNameL, 2, 0, 1, 25)
    self.LayoutL.addWidget(self.MarketCapValueL, 2, 25, 1, 25)
    self.LayoutL.addWidget(self.PENameL, 3, 0, 1, 25)
    self.LayoutL.addWidget(self.PEValueL, 3, 25, 1, 25)
    self.LayoutL.addWidget(self.ForwardPENameL, 4, 0, 1, 25)
    self.LayoutL.addWidget(self.ForwardPEValueL, 4, 25, 1, 25)
    self.LayoutL.addWidget(self.PEGNameL, 5, 0, 1, 25)
    self.LayoutL.addWidget(self.PEGValueL, 5, 25, 1, 25)
    self.LayoutL.addWidget(self.PBNameL, 6, 0, 1, 25)
    self.LayoutL.addWidget(self.PBValueL, 6, 25, 1, 25)
    self.LayoutL.addWidget(self.PSNameL, 7, 0, 1, 25)
    self.LayoutL.addWidget(self.PSValueL, 7, 25, 1, 25)
    self.LayoutL.addWidget(self.ProfitabilitySubTitleL, 1, 50, 1, 50)
    self.LayoutL.addWidget(self.ROENameL, 2, 50, 1, 25)
    self.LayoutL.addWidget(self.ROEValueL, 2, 75, 1, 25)
    self.LayoutL.addWidget(self.ROANameL, 3, 50, 1, 25)
    self.LayoutL.addWidget(self.ROAValueL, 3, 75, 1, 25)
    self.LayoutL.addWidget(self.ROINameL, 4, 50, 1, 25)
    self.LayoutL.addWidget(self.ROIValueL, 4, 75, 1, 25)
    self.LayoutL.addWidget(self.NetMarginNameL, 5, 50, 1, 25)
    self.LayoutL.addWidget(self.NetMarginValueL, 5, 75, 1, 25)
    self.LayoutL.addWidget(self.OperatingMarginNameL, 6, 50, 1, 25)
    self.LayoutL.addWidget(self.OperatingMarginValueL, 6, 75, 1, 25)
    self.LayoutL.addWidget(self.GrossMarginNameL, 7, 50 ,1, 25)
    self.LayoutL.addWidget(self.GrossMarginValueL, 7, 75, 1, 25)
    self.LayoutL.addWidget(self.BalanceSubTitleL, 8, 0, 1, 50)
    self.LayoutL.addWidget(self.AssetsNameL, 9, 0, 1, 25)
    self.LayoutL.addWidget(self.AssetsValueL, 9, 25, 1, 25)
    self.LayoutL.addWidget(self.LiabilitiesNameL, 10, 0, 1, 25)
    self.LayoutL.addWidget(self.LiabilitiesValueL, 10, 25, 1, 25)
    self.LayoutL.addWidget(self.EquityNameL, 11, 0, 1, 25)
    self.LayoutL.addWidget(self.EquityValueL, 11, 25, 1, 25)
    self.LayoutL.addWidget(self.CashNameL, 12, 0, 1, 25)
    self.LayoutL.addWidget(self.CashValueL, 12, 25, 1, 25)
    self.LayoutL.addWidget(self.DebtNameL, 13, 0, 1, 25)
    self.LayoutL.addWidget(self.DebtValueL, 13, 25, 1, 25)
    self.LayoutL.addWidget(self.FinancialReportsTitleL, 14, 0, 1, 100)
    self.LayoutL.addWidget(self.IncomeStatementSubTitleL, 15, 0, 1, 50)
    self.LayoutL.addWidget(self.RevenueNameL, 16, 0, 1, 25)
    self.LayoutL.addWidget(self.RevenueValueL, 16, 25, 1, 25)
    self.LayoutL.addWidget(self.GrossProfitNameL, 17, 0, 1, 25)
    self.LayoutL.addWidget(self.GrossProfitValueL, 17, 25, 1, 25)
    self.LayoutL.addWidget(self.OperatingIncomeNameL, 18, 0, 1, 25)
    self.LayoutL.addWidget(self.OperatingIncomeValueL, 18, 25, 1, 25)
    self.LayoutL.addWidget(self.NetIncomeNameL, 19, 0, 1, 25)
    self.LayoutL.addWidget(self.NetIncomeValueL, 19, 25, 1, 25)
    self.LayoutL.addWidget(self.EPSIncomeNameL, 20, 0, 1, 25)
    self.LayoutL.addWidget(self.EPSIncomeValueL, 20, 25, 1, 25)
    self.LayoutL.addWidget(self.BalanceSheetSubTitleL, 15, 50, 1, 50)
    self.LayoutL.addWidget(self.TotalAssetsNameL, 16, 50, 1, 25)
    self.LayoutL.addWidget(self.TotalAssetsValueL, 16, 75, 1, 25)
    self.LayoutL.addWidget(self.TotalLiabilitiesNameL, 17, 50, 1, 25)
    self.LayoutL.addWidget(self.TotalLiabilitiesValueL, 17, 75, 1, 25)
    self.LayoutL.addWidget(self.ShareholderEqulityNameL, 18, 50, 1, 25)
    self.LayoutL.addWidget(self.ShareholderEqulityValueL, 18, 75, 1, 25)
    self.LayoutL.addWidget(self.CashFlowSubTitleL, 21, 0, 1, 50)
    self.LayoutL.addWidget(self.OperatingCashFlowNameL, 22, 0, 1, 25)
    self.LayoutL.addWidget(self.OperatingCashFlowValueL, 22, 25, 1, 25)
    self.LayoutL.addWidget(self.InvestingCashFlowNameL, 23, 0, 1, 25)
    self.LayoutL.addWidget(self.InvestingCashFlowValueL, 23, 25, 1, 25)
    self.LayoutL.addWidget(self.FinancingCashFlowNameL, 24, 0, 1, 25)
    self.LayoutL.addWidget(self.FinancingCashFlowValueL, 24, 25, 1, 25)
    self.LayoutL.addWidget(self.FreeCashFlowNameL, 25, 0, 1, 25)
    self.LayoutL.addWidget(self.FreeCashFlowValueL, 25, 25, 1, 25)
    self.LayoutL.addWidget(self.DividendDataSubTitleL, 21, 50, 1, 50)
    self.LayoutL.addWidget(self.DividendYieldNameL, 22, 50, 1, 25)
    self.LayoutL.addWidget(self.DividendYieldValueL, 22, 75, 1, 25)
    self.LayoutL.addWidget(self.DividendPerShareNameL, 23, 50, 1, 25)
    self.LayoutL.addWidget(self.DividendPerShareValueL, 23, 75, 1, 25)
    self.LayoutL.addWidget(self.PayoutRatioNameL, 24, 50, 1, 25)
    self.LayoutL.addWidget(self.PayoutRatioValueL, 24, 75, 1, 25)
    self.LayoutL.addWidget(self.DividendHistoryNameL, 25, 50, 1, 25)
    self.LayoutL.addWidget(self.DividendHistoryValueL, 25, 75, 1, 25)
    self.LayoutL.addWidget(self.ExDividendNameL, 26, 50, 1, 25)
    self.LayoutL.addWidget(self.ExDividendValueL, 26, 75, 1, 25)
    self.LayoutL.addWidget(self.PaymentDateNameL, 27, 50, 1, 25)
    self.LayoutL.addWidget(self.PaymentDateValueL, 27, 75, 1, 25)
    self.LayoutL.addWidget(self.CorporationDataTitleL, 28, 0, 1, 100)
    self.LayoutL.addWidget(self.CorporateActionsSubTitleL, 29, 0, 1, 50)
    self.LayoutL.addWidget(self.StockSplitNameL, 30, 0, 1, 25)
    self.LayoutL.addWidget(self.StockSplitValueL, 30, 25, 1, 25)
    self.LayoutL.addWidget(self.ReverseSplitNameL, 31, 0, 1, 25)
    self.LayoutL.addWidget(self.ReverseSplitValueL, 31, 25, 1, 25)
    self.LayoutL.addWidget(self.MergersNameL, 32, 0, 1, 25)
    self.LayoutL.addWidget(self.MergersValueL, 32, 25, 1, 25)
    self.LayoutL.addWidget(self.AcquisitionsNameL, 33, 0, 1, 25)
    self.LayoutL.addWidget(self.AcquisitionsValueL, 33, 25, 1, 25)
    self.LayoutL.addWidget(self.BuyBacksNameL, 34, 0, 1, 25)
    self.LayoutL.addWidget(self.BuyBacksValueL, 34, 25, 1, 25)
    self.LayoutL.addWidget(self.EventsSubTitleL, 29, 50, 1, 50)
    self.LayoutL.addWidget(self.EarningsDateNameL, 30, 50, 1, 25)
    self.LayoutL.addWidget(self.EarningsDateValueL, 30, 75, 1, 25)
    self.LayoutL.addWidget(self.AGMNameL, 31, 50, 1, 25)
    self.LayoutL.addWidget(self.AGMValueL, 31, 75, 1, 25)
    self.LayoutL.addWidget(self.InvestorDayNameL, 32, 50, 1, 25)
    self.LayoutL.addWidget(self.InvestorDayValueL, 32, 75, 1, 25)
    self.LayoutL.addWidget(self.OwnershipDataTitleL, 33, 0, 1, 100)
    self.LayoutL.addWidget(self.ShareholdingSubTitleL, 34, 0, 1, 50)
    self.LayoutL.addWidget(self.InstitutionalOwnershipNameL, 35, 0, 1, 25)
    self.LayoutL.addWidget(self.InstitutionalOwnershipValueL, 35, 25, 1, 25)
    self.LayoutL.addWidget(self.InsiderOwnershipNameL, 36, 0, 1, 25)
    self.LayoutL.addWidget(self.InsiderOwnershipValueL, 36, 25, 1, 25)
    self.LayoutL.addWidget(self.TopShareholdersNameL, 37, 0, 1, 25)
    self.LayoutL.addWidget(self.TopShareholdersValueL, 37, 25, 1, 25)
    self.LayoutL.addWidget(self.InsiderTradingSubTitleL, 34, 50, 1, 50)
    self.LayoutL.addWidget(self.InsiderBuysNameL, 35, 50, 1, 25)
    self.LayoutL.addWidget(self.InsiderBuysValueL, 35, 75, 1, 25)
    self.LayoutL.addWidget(self.InsiderSellsNameL, 36, 50, 1, 25)
    self.LayoutL.addWidget(self.InsiderSellsValueL, 36, 75, 1, 25)
    self.LayoutL.addWidget(self.AnaliticalDataTitleL, 37, 0, 1, 100)
    self.LayoutL.addWidget(self.MovingAveragesNameL, 38, 0, 1, 25)
    self.LayoutL.addWidget(self.MovingAveragesValueL, 38, 25, 1, 25)
    self.LayoutL.addWidget(self.RSINameL, 38, 50, 1, 25)
    self.LayoutL.addWidget(self.RSIValueL, 38, 75, 1, 25)
    self.LayoutL.addWidget(self.MACDNameL, 39, 0, 1, 25)
    self.LayoutL.addWidget(self.MACDValueL, 39, 25, 1, 25)
    self.LayoutL.addWidget(self.BollingerBandsNameL, 39, 50, 1, 25)
    self.LayoutL.addWidget(self.BollingerBandsValueL, 39, 75, 1, 25)
    self.LayoutL.addWidget(self.MomentumNameL, 40, 0, 1, 25)
    self.LayoutL.addWidget(self.MomentumValueL, 40, 25, 1, 25)
    self.LayoutL.addWidget(self.VolatillityNameL, 40, 50, 1, 52)
    self.LayoutL.addWidget(self.VolatillityValueL, 40, 75, 1, 25)
    self.LayoutL.addWidget(self.ESGDataTitleL, 41, 0, 1, 100)
    self.LayoutL.addWidget(self.ESGScoreNameL, 42, 0, 1, 25)
    self.LayoutL.addWidget(self.ESGScoreValueL, 42, 25, 1, 25)
    self.LayoutL.addWidget(self.EnvironmentalScoreNameL, 42, 50, 1, 25)
    self.LayoutL.addWidget(self.EnvironmentalScoreValueL, 42, 75, 1, 25)
    self.LayoutL.addWidget(self.GovernanceScoreNameL, 43, 0, 1, 25)
    self.LayoutL.addWidget(self.GovernanceScoreValueL, 43, 25, 1, 25)
    self.LayoutL.setSpacing(0)
    self.LayoutL.setContentsMargins(0,0,0,0)
    for i in range(100):
        self.LayoutL.setColumnStretch(i, 1)
    self.WidgetW.setLayout(self.LayoutL)
    self.show()
    self.setWidget(self.WidgetW)
    self.setWidgetResizable(True)
    self.FundamentalDataTitleL.setAlignment(Qt.AlignCenter)
    self.IndicatorsSubTitleL.setAlignment(Qt.AlignCenter)
    self.MarketCapNameL.setAlignment(Qt.AlignCenter)
    self.MarketCapValueL.setAlignment(Qt.AlignCenter)
    self.PENameL.setAlignment(Qt.AlignCenter)
    self.PEValueL.setAlignment(Qt.AlignCenter)
    self.PEGNameL.setAlignment(Qt.AlignCenter)
    self.PEGValueL.setAlignment(Qt.AlignCenter)
    self.PBNameL.setAlignment(Qt.AlignCenter)
    self.PBValueL.setAlignment(Qt.AlignCenter)
    self.PSNameL.setAlignment(Qt.AlignCenter)
    self.PSValueL.setAlignment(Qt.AlignCenter)
    self.ProfitabilitySubTitleL.setAlignment(Qt.AlignCenter)
    self.ROENameL.setAlignment(Qt.AlignCenter)
    self.ROEValueL.setAlignment(Qt.AlignCenter)
    self.ROANameL.setAlignment(Qt.AlignCenter)
    self.ROAValueL.setAlignment(Qt.AlignCenter)
    self.ROINameL.setAlignment(Qt.AlignCenter)
    self.ROIValueL.setAlignment(Qt.AlignCenter)
    self.NetMarginNameL.setAlignment(Qt.AlignCenter)
    self.NetMarginValueL.setAlignment(Qt.AlignCenter)
    self.OperatingMarginNameL.setAlignment(Qt.AlignCenter)
    self.OperatingMarginValueL.setAlignment(Qt.AlignCenter)
    self.GrossMarginNameL.setAlignment(Qt.AlignCenter)
    self.GrossMarginValueL.setAlignment(Qt.AlignCenter)
    self.BalanceSubTitleL.setAlignment(Qt.AlignCenter)
    self.AssetsNameL.setAlignment(Qt.AlignCenter)
    self.AssetsValueL.setAlignment(Qt.AlignCenter)
    self.LiabilitiesNameL.setAlignment(Qt.AlignCenter)
    self.LiabilitiesValueL.setAlignment(Qt.AlignCenter)
    self.EquityNameL.setAlignment(Qt.AlignCenter)
    self.EquityValueL.setAlignment(Qt.AlignCenter)
    self.CashNameL.setAlignment(Qt.AlignCenter)
    self.CashValueL.setAlignment(Qt.AlignCenter)
    self.DebtNameL.setAlignment(Qt.AlignCenter)
    self.DebtValueL.setAlignment(Qt.AlignCenter)
    self.FinancialReportsTitleL.setAlignment(Qt.AlignCenter)
    self.IncomeStatementSubTitleL.setAlignment(Qt.AlignCenter)
    self.RevenueNameL.setAlignment(Qt.AlignCenter)
    self.RevenueValueL.setAlignment(Qt.AlignCenter)
    self.GrossProfitNameL.setAlignment(Qt.AlignCenter)
    self.GrossProfitValueL.setAlignment(Qt.AlignCenter)
    self.OperatingIncomeNameL.setAlignment(Qt.AlignCenter)
    self.OperatingIncomeValueL.setAlignment(Qt.AlignCenter)
    self.NetIncomeNameL.setAlignment(Qt.AlignCenter)
    self.NetIncomeValueL.setAlignment(Qt.AlignCenter)
    self.EPSIncomeNameL.setAlignment(Qt.AlignCenter)
    self.EPSIncomeValueL.setAlignment(Qt.AlignCenter)
    self.BalanceSheetSubTitleL.setAlignment(Qt.AlignCenter)
    self.TotalAssetsNameL.setAlignment(Qt.AlignCenter)
    self.TotalAssetsValueL.setAlignment(Qt.AlignCenter)
    self.TotalLiabilitiesNameL.setAlignment(Qt.AlignCenter)
    self.TotalLiabilitiesValueL.setAlignment(Qt.AlignCenter)
    self.ShareholderEqulityNameL.setAlignment(Qt.AlignCenter)
    self.ShareholderEqulityValueL.setAlignment(Qt.AlignCenter)
    self.CashFlowSubTitleL.setAlignment(Qt.AlignCenter)
    self.OperatingCashFlowNameL.setAlignment(Qt.AlignCenter)
    self.OperatingCashFlowValueL.setAlignment(Qt.AlignCenter)
    self.InvestingCashFlowNameL.setAlignment(Qt.AlignCenter)
    self.InvestingCashFlowValueL.setAlignment(Qt.AlignCenter)
    self.FinancingCashFlowNameL.setAlignment(Qt.AlignCenter)
    self.FinancingCashFlowValueL.setAlignment(Qt.AlignCenter)
    self.FreeCashFlowNameL.setAlignment(Qt.AlignCenter)
    self.FreeCashFlowValueL.setAlignment(Qt.AlignCenter)
    self.DividendDataSubTitleL.setAlignment(Qt.AlignCenter)
    self.DividendYieldNameL.setAlignment(Qt.AlignCenter)
    self.DividendYieldValueL.setAlignment(Qt.AlignCenter)
    self.DividendPerShareNameL.setAlignment(Qt.AlignCenter)
    self.DividendPerShareValueL.setAlignment(Qt.AlignCenter)
    self.PayoutRatioNameL.setAlignment(Qt.AlignCenter)
    self.PayoutRatioValueL.setAlignment(Qt.AlignCenter)
    self.DividendHistoryNameL.setAlignment(Qt.AlignCenter)
    self.DividendHistoryValueL.setAlignment(Qt.AlignCenter)
    self.ExDividendNameL.setAlignment(Qt.AlignCenter)
    self.ExDividendValueL.setAlignment(Qt.AlignCenter)
    self.PaymentDateNameL.setAlignment(Qt.AlignCenter)
    self.PaymentDateValueL.setAlignment(Qt.AlignCenter)
    self.CorporationDataTitleL.setAlignment(Qt.AlignCenter)
    self.CorporateActionsSubTitleL.setAlignment(Qt.AlignCenter)
    self.StockSplitNameL.setAlignment(Qt.AlignCenter)
    self.StockSplitValueL.setAlignment(Qt.AlignCenter)
    self.ReverseSplitNameL.setAlignment(Qt.AlignCenter)
    self.ReverseSplitValueL.setAlignment(Qt.AlignCenter)
    self.MergersNameL.setAlignment(Qt.AlignCenter)
    self.MergersValueL.setAlignment(Qt.AlignCenter)
    self.AcquisitionsNameL.setAlignment(Qt.AlignCenter)
    self.AcquisitionsValueL.setAlignment(Qt.AlignCenter)
    self.BuyBacksNameL.setAlignment(Qt.AlignCenter)
    self.BuyBacksValueL.setAlignment(Qt.AlignCenter)
    self.EventsSubTitleL.setAlignment(Qt.AlignCenter)
    self.EarningsDateNameL.setAlignment(Qt.AlignCenter)
    self.EarningsDateValueL.setAlignment(Qt.AlignCenter)
    self.AGMNameL.setAlignment(Qt.AlignCenter)
    self.AGMValueL.setAlignment(Qt.AlignCenter)
    self.InvestorDayNameL.setAlignment(Qt.AlignCenter)
    self.InvestorDayValueL.setAlignment(Qt.AlignCenter)
    self.OwnershipDataTitleL.setAlignment(Qt.AlignCenter)
    self.ShareholdingSubTitleL.setAlignment(Qt.AlignCenter)
    self.InstitutionalOwnershipNameL.setAlignment(Qt.AlignCenter)
    self.InstitutionalOwnershipValueL.setAlignment(Qt.AlignCenter)
    self.InsiderOwnershipNameL.setAlignment(Qt.AlignCenter)
    self.InsiderOwnershipValueL.setAlignment(Qt.AlignCenter)
    self.TopShareholdersNameL.setAlignment(Qt.AlignCenter)
    self.TopShareholdersValueL.setAlignment(Qt.AlignCenter)
    self.InsiderTradingSubTitleL.setAlignment(Qt.AlignCenter)
    self.InsiderBuysNameL.setAlignment(Qt.AlignCenter)
    self.InsiderBuysValueL.setAlignment(Qt.AlignCenter)
    self.InsiderSellsNameL.setAlignment(Qt.AlignCenter)
    self.InsiderSellsValueL.setAlignment(Qt.AlignCenter)
    self.AnaliticalDataTitleL.setAlignment(Qt.AlignCenter)
    self.MovingAveragesNameL.setAlignment(Qt.AlignCenter)
    self.MovingAveragesValueL.setAlignment(Qt.AlignCenter)
    self.RSINameL.setAlignment(Qt.AlignCenter)
    self.RSIValueL.setAlignment(Qt.AlignCenter)
    self.MACDNameL.setAlignment(Qt.AlignCenter)
    self.MACDValueL.setAlignment(Qt.AlignCenter)
    self.BollingerBandsNameL.setAlignment(Qt.AlignCenter)
    self.BollingerBandsValueL.setAlignment(Qt.AlignCenter)
    self.MomentumNameL.setAlignment(Qt.AlignCenter)
    self.MomentumValueL.setAlignment(Qt.AlignCenter)
    self.VolatillityNameL.setAlignment(Qt.AlignCenter)
    self.VolatillityValueL.setAlignment(Qt.AlignCenter)
    self.ESGDataTitleL.setAlignment(Qt.AlignCenter)
    self.ESGScoreNameL.setAlignment(Qt.AlignCenter)
    self.ESGScoreValueL.setAlignment(Qt.AlignCenter)
    self.EnvironmentalScoreNameL.setAlignment(Qt.AlignCenter)
    self.EnvironmentalScoreValueL.setAlignment(Qt.AlignCenter)
    self.GovernanceScoreNameL.setAlignment(Qt.AlignCenter)
    self.GovernanceScoreValueL.setAlignment(Qt.AlignCenter)
    self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.WidgetW.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.FundamentalDataTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.IndicatorsSubTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.MarketCapNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.MarketCapValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PENameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PEValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PEGNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PEGValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PBNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PBValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PSNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PSValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ProfitabilitySubTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ROENameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ROEValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ROANameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ROAValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ROINameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ROIValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.NetMarginNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.NetMarginValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.OperatingMarginNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.OperatingMarginValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.GrossMarginNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.GrossMarginValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.BalanceSubTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.AssetsNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.AssetsValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.LiabilitiesNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.LiabilitiesValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.EquityNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.EquityValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CashNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CashValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.DebtNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.DebtValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.FinancialReportsTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.IncomeStatementSubTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.RevenueNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.RevenueValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.GrossProfitNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.GrossProfitValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.OperatingIncomeNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.OperatingIncomeValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.NetIncomeNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.NetIncomeValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.EPSIncomeNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.EPSIncomeValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.BalanceSheetSubTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.TotalAssetsNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.TotalAssetsValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.TotalLiabilitiesNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.TotalLiabilitiesValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ShareholderEqulityNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ShareholderEqulityValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CashFlowSubTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.OperatingCashFlowNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.OperatingCashFlowValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.InvestingCashFlowNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.InvestingCashFlowValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.FinancingCashFlowNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.FinancingCashFlowValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.FreeCashFlowNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.FreeCashFlowValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.DividendDataSubTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.DividendYieldNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.DividendYieldValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.DividendPerShareNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.DividendPerShareValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PayoutRatioNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PayoutRatioValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.DividendHistoryNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.DividendHistoryValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ExDividendNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ExDividendValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PaymentDateNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PaymentDateValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CorporationDataTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CorporateActionsSubTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.StockSplitNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.StockSplitValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ReverseSplitNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ReverseSplitValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.MergersNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.MergersValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.AcquisitionsNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.AcquisitionsValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.BuyBacksNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.BuyBacksValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.EventsSubTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.EarningsDateNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.EarningsDateValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.AGMNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.AGMValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.InvestorDayNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.InvestorDayValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.OwnershipDataTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ShareholdingSubTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.InstitutionalOwnershipNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.InstitutionalOwnershipValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.InsiderOwnershipNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.InsiderOwnershipValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.TopShareholdersNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.TopShareholdersValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.InsiderTradingSubTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.InsiderBuysNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.InsiderBuysValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.InsiderSellsNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.InsiderSellsValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.AnaliticalDataTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.MovingAveragesNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.MovingAveragesValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.RSINameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.RSIValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.MACDNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.MACDValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.BollingerBandsNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.BollingerBandsValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.MomentumNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.MomentumValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.VolatillityNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.VolatillityValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ESGDataTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ESGScoreNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ESGScoreValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.EnvironmentalScoreNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.EnvironmentalScoreValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.GovernanceScoreNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.GovernanceScoreValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

def StockReloadStyle(self):
    t = self.Theme
    m = open(f'{self.Path}/APP_FILES/PYTHON/ObjectStats/BMain.css').read()
    c = open(f'{self.Path}/APP_FILES/PYTHON/ObjectStats/B{t}.css').read()
    self.setStyleSheet(m+c)

def StockRetranslate(self):
    t = json.load(open(f'{self.Path}/APP_FILES/PYTHON/ObjectStats/CStockTranslate.json', 'r'))
    l = self.Language
    self.FundamentalDataTitleL.setText(t['FundamentalDataTitleL'][l])
    self.IndicatorsSubTitleL.setText(t['IndicatorsSubTitleL'][l])
    self.MarketCapNameL.setText(t['MarketCapNameL'][l]+':')
    self.PENameL.setText(t['PENameL'][l]+':')
    self.ForwardPENameL.setText(t['ForwardPENameL'][l]+':')
    self.PEGNameL.setText(t['PEGNameL'][l]+':')
    self.PBNameL.setText(t['PBNameL'][l]+':')
    self.PSNameL.setText(t['PSNameL'][l]+':')
    self.ProfitabilitySubTitleL.setText(t['ProfitabilitySubTitleL'][l])
    self.ROENameL.setText(t['ROENameL'][l]+':')
    self.ROANameL.setText(t['ROANameL'][l]+':')
    self.ROINameL.setText(t['ROINameL'][l]+':')
    self.NetMarginNameL.setText(t['NetMarginNameL'][l]+':')
    self.OperatingMarginNameL.setText(t['OperatingMarginNameL'][l]+':')
    self.GrossMarginNameL.setText(t['GrossMarginNameL'][l]+':')
    self.BalanceSubTitleL.setText(t['BalanceSubTitleL'][l])
    self.AssetsNameL.setText(t['AssetsNameL'][l]+':')
    self.LiabilitiesNameL.setText(t['LiabilitiesNameL'][l]+':')
    self.EquityNameL.setText(t['EquityNameL'][l]+':')
    self.CashNameL.setText(t['CashNameL'][l]+':')
    self.DebtNameL.setText(t['DebtNameL'][l]+':')
    self.FinancialReportsTitleL.setText(t['FinancialReportsTitleL'][l])
    self.IncomeStatementSubTitleL.setText(t['IncomeStatementSubTitleL'][l])
    self.RevenueNameL.setText(t['RevenueNameL'][l]+':')
    self.GrossProfitNameL.setText(t['GrossProfitNameL'][l]+':')
    self.OperatingIncomeNameL.setText(t['OperatingIncomeNameL'][l]+':')
    self.NetIncomeNameL.setText(t['NetIncomeNameL'][l]+':')
    self.EPSIncomeNameL.setText(t['EPSIncomeNameL'][l]+':')
    self.BalanceSheetSubTitleL.setText(t['BalanceSheetSubTitleL'][l])
    self.TotalAssetsNameL.setText(t['TotalAssetsNameL'][l]+':')
    self.TotalLiabilitiesNameL.setText(t['TotalLiabilitiesNameL'][l]+':')
    self.ShareholderEqulityNameL.setText(t['ShareholderEqulityNameL'][l]+':')
    self.CashFlowSubTitleL.setText(t['CashFlowSubTitleL'][l])
    self.OperatingCashFlowNameL.setText(t['OperatingCashFlowNameL'][l]+':')
    self.InvestingCashFlowNameL.setText(t['InvestingCashFlowNameL'][l]+':')
    self.FinancingCashFlowNameL.setText(t['FinancingCashFlowNameL'][l]+':')
    self.FreeCashFlowNameL.setText(t['FreeCashFlowNameL'][l]+':')
    self.DividendDataSubTitleL.setText(t['DividendDataSubTitleL'][l])
    self.DividendYieldNameL.setText(t['DividendYieldNameL'][l]+':')
    self.DividendPerShareNameL.setText(t['DividendPerShareNameL'][l]+':')
    self.PayoutRatioNameL.setText(t['PayoutRatioNameL'][l]+':')
    self.DividendHistoryNameL.setText(t['DividendHistoryNameL'][l]+':')
    self.ExDividendNameL.setText(t['ExDividendNameL'][l]+':')
    self.PaymentDateNameL.setText(t['PaymentDateNameL'][l]+':')
    self.CorporationDataTitleL.setText(t['CorporationDataTitleL'][l])
    self.CorporateActionsSubTitleL.setText(t['CorporateActionsSubTitleL'][l])
    self.StockSplitNameL.setText(t['StockSplitNameL'][l]+':')
    self.ReverseSplitNameL.setText(t['ReverseSplitNameL'][l]+':')
    self.MergersNameL.setText(t['MergersNameL'][l]+':')
    self.AcquisitionsNameL.setText(t['AcquisitionsNameL'][l]+':')
    self.BuyBacksNameL.setText(t['BuyBacksNameL'][l]+':')
    self.EventsSubTitleL.setText(t['EventsSubTitleL'][l])
    self.EarningsDateNameL.setText(t['EarningsDateNameL'][l]+':')
    self.AGMNameL.setText(t['AGMNameL'][l]+':')
    self.InvestorDayNameL.setText(t['InvestorDayNameL'][l]+':')
    self.OwnershipDataTitleL.setText(t['OwnershipDataTitleL'][l])
    self.ShareholdingSubTitleL.setText(t['ShareholdingSubTitleL'][l])
    self.InstitutionalOwnershipNameL.setText(t['InstitutionalOwnershipNameL'][l]+':')
    self.InsiderOwnershipNameL.setText(t['InsiderOwnershipNameL'][l]+':')
    self.TopShareholdersNameL.setText(t['TopShareholdersNameL'][l]+':')
    self.InsiderTradingSubTitleL.setText(t['InsiderTradingSubTitleL'][l])
    self.InsiderBuysNameL.setText(t['InsiderBuysNameL'][l]+':')
    self.InsiderSellsNameL.setText(t['InsiderSellsNameL'][l]+':')
    self.AnaliticalDataTitleL.setText(t['AnaliticalDataTitleL'][l]+':')
    self.MovingAveragesNameL.setText(t['MovingAveragesNameL'][l]+':')
    self.RSINameL.setText(t['RSINameL'][l]+':')
    self.MACDNameL.setText(t['MACDNameL'][l]+':')
    self.BollingerBandsNameL.setText(t['BollingerBandsNameL'][l]+':')
    self.MomentumNameL.setText(t['MomentumNameL'][l]+':')
    self.VolatillityNameL.setText(t['VolatillityNameL'][l]+':')
    self.ESGDataTitleL.setText(t['ESGDataTitleL'][l])
    self.ESGScoreNameL.setText(t['ESGScoreNameL'][l]+':')
    self.EnvironmentalScoreNameL.setText(t['EnvironmentalScoreNameL'][l]+':')
    self.GovernanceScoreNameL.setText(t['GovernanceScoreNameL'][l]+':')
    