#   --- Improt ---
import json
from PyQt5.QtWidgets import (
    QSizePolicy
)
from PyQt5.QtCore import (
    Qt,
    QSize
)
from PyQt5.QtGui import (
    QPixmap,
    QIcon,
    QPainter
)
from PyQt5.QtSvg import (
    QSvgRenderer
)

def StockUi(self):
    self.Widget.setObjectName('Widget')
    self.TitleL.setObjectName('TitleL')
    self.FundamentalDataTitleL.setObjectName('FundamentalDataTitleL')
    self.IndicatorsSubTitleL.setObjectName('IndicatorsSubTitleL')
    self.MarketCapNameL.setObjectName('MarketCapNameL')
    self.MarketCapValueL.setObjectName('MarketCapValueL')
    self.PENameL.setObjectName('PENameL')
    self.PEValueL.setObjectName('PEValueL')
    self.ForwardPENameL.setObjectName('ForwardPENameL')
    self.ForwardPEValueL.setObjectName('ForwardPEValueL')
    self.PEGNameL.setObjectName('PEGNameL')
    self.PEGValueL.setObjectName('PEGValueL')
    self.PBNameL.setObjectName('PBNameL')
    self.PBValueL.setObjectName('PBValueL')
    self.PSNameL.setObjectName('PSNameL')
    self.PSValueL.setObjectName('PSValueL')
    self.ProfitabilitySubTitleL.setObjectName('ProfitabilitySubTitleL')
    self.ROENameL.setObjectName('ROENameL')
    self.ROEValueL.setObjectName('ROEValueL')
    self.ROANameL.setObjectName('ROANameL')
    self.ROAValueL.setObjectName('')
    self.ROINameL.setObjectName('')
    self.ROIValueL.setObjectName('')
    self.NetMarginNameL.setObjectName('')
    self.NetMarginValueL.setObjectName('')
    self.OperatingMarginNameL.setObjectName('')
    self.OperatingMarginValueL.setObjectName('')
    self.GrossMarginNameL.setObjectName('')
    self.GrossMarginValueL.setObjectName('')
    self.BalanceSubTitleL.setObjectName('')
    self.AssetsNameL.setObjectName('')
    self.AssetsValueL.setObjectName('')
    self.LiabilitiesNameL.setObjectName('')
    self.LiabilitiesValueL.setObjectName('')
    self.EquityNameL.setObjectName('')
    self.EquityValueL.setObjectName('')
    self.CashNameL.setObjectName('')
    self.CashValueL.setObjectName('')
    self.DebtNameL.setObjectName('')
    self.DebtValueL.setObjectName('')
    self.FinancialReportsTitleL.setObjectName('')
    self.IncomeStatementSubTitleL.setObjectName('')
    self.RevenueNameL.setObjectName('')
    self.RevenueValueL.setObjectName('')
    self.GrossProfitNameL.setObjectName('')
    self.GrossProfitValueL.setObjectName('')
    self.OperatingIncomeNameL.setObjectName('')
    self.OperatingIncomeValueL.setObjectName('')
    self.NetIncomeNameL.setObjectName('')
    self.NetIncomeValueL.setObjectName('')
    self.EPSIncomeNameL.setObjectName('')
    self.EPSIncomeValueL.setObjectName('')
        self.BalanceSheetSubTitleL.setObjectName('')
        self.TotalAssetsNameL.setObjectName('')
        self.TotalAssetsValueL.setObjectName('')
        self.TotalLiabilitiesNameL.setObjectName('')
        self.TotalLiabilitiesValueL.setObjectName('')
        self.ShareholderEqulityNameL.setObjectName('')
        self.ShareholderEqulityValueL.setObjectName('')
        self.CashFlowSubTitleL.setObjectName('')
        self.OperatingCashFlowNameL.setObjectName('')
        self.OperatingCashFlowValueL.setObjectName('')
        self.InvestingCashFlowNameL.setObjectName('')
        self.InvestingCashFlowValueL.setObjectName('')
        self.FinancingCashFlowNameL.setObjectName('')
        self.FinancingCashFlowValueL.setObjectName('')
        self.FreeCashFlowNameL.setObjectName('')
        self.FreeCashFlowValueL.setObjectName('')
        self.DividendDataSubTitleL.setObjectName('')
        self.DividendYieldNameL.setObjectName('')
        self.DividendYieldValueL.setObjectName('')
        self.DividendPerShareNameL.setObjectName('')
        self.DividendPerShareValueL.setObjectName('')
        self.PayoutRatioNameL.setObjectName('')
        self.PayoutRatioValueL.setObjectName('')
        self.DividendHistoryNameL.setObjectName('')
        self.DividendHistoryValueL.setObjectName('')
        self.ExDividendNameL.setObjectName('')
        self.ExDividendValueL.setObjectName('')
        self.PaymentDateNameL.setObjectName('')
        self.PaymentDateValueL.setObjectName('')
        self.CorporationDataTitleL.setObjectName('')
        self.CorporateActionsSubTitleL.setObjectName('')
        self.StockSplitNameL.setObjectName('')
        self.StockSplitValueL.setObjectName('')
        self.ReverseSplitNameL.setObjectName('')
        self.ReverseSplitValueL.setObjectName('')
        self.MergersNameL.setObjectName('')
        self.MergersValueL.setObjectName('')
        self.AcquisitionsNameL.setObjectName('')
        self.AcquisitionsValueL.setObjectName('')
        self.BuyBacksNameL.setObjectName('')
        self.BuyBacksValueL.setObjectName('')
        self.EventsSubTitleL.setObjectName('')
        self.EarningsDateNameL.setObjectName('')
        self.EarningsDateValueL.setObjectName('')
        self.AGMNameL.setObjectName('')
        self.AGMValueL.setObjectName('')
        self.InvestorDayNameL.setObjectName('')
        self.InvestorDayValueL.setObjectName('')
        self.OwnershipDataTitleL.setObjectName('')
        self.ShareholdingSubTitleL.setObjectName('')
        self.InstitutionalOwnershipNameL.setObjectName('')
        self.InstitutionalOwnershipValueL.setObjectName('')
        self.InsiderOwnershipNameL.setObjectName('')
        self.InsiderOwnershipValueL.setObjectName('')
        self.TopShareholdersNameL.setObjectName('')
        self.TopShareholdersValueL.setObjectName('')
        self.InsiderTradingSubTitleL.setObjectName('')
        self.InsiderBuysNameL.setObjectName('')
        self.InsiderBuysValueL.setObjectName('')
        self.InsiderSellsNameL.setObjectName('')
        self.InsiderSellsValueL.setObjectName('')
        self.AnaliticalDataTitleL.setObjectName('')
        self.MovingAveragesNameL.setObjectName('')
        self.MovingAveragesValueL.setObjectName('')
        self.RSINameL.setObjectName('')
        self.RSIValueL.setObjectName('')
        self.MACDNameL.setObjectName('')
        self.MACDValueL.setObjectName('')
        self.BollingerBandsNameL.setObjectName('')
        self.BollingerBandsValueL.setObjectName('')
        self.MomentumNameL.setObjectName('')
        self.MomentumValueL.setObjectName('')
        self.VolatillityNameL.setObjectName('')
        self.VolatillityValueL.setObjectName('')
        self.ESGDataTitleL.setObjectName('')
        self.ESGScoreNameL.setObjectName('')
        self.ESGScoreValueL.setObjectName('')
        self.EnvironmentalScoreNameL.setObjectName('')
        self.EnvironmentalScoreValueL.setObjectName('')
        self.GovernanceScoreNameL.setObjectName('')
        self.GovernanceScoreValueL.setObjectName('')

        self.FundamentalDataTitleL.setProperty('class', 'Title')

        self.IndicatorsSubTitleL.setProperty('class', 'SubTitle')

        self.MarketCapNameL.setProperty('class', 'Name')

        self.MarketCapValueL.setProperty('class', 'Value')


        self.Layout.setSpacing(0)
        self.Layout.setContentsMargins(0,0,0,0)
        for i in range(100):
            self.Layout.setColumnStretch(i, 1)
        self.Widget.setLayout(self.Layout)

        self.show()
        self.setWidget(self.Widget)
        self.setWidgetResizable(True)

        self.TitleL.setAlignment(Qt.AlignCenter)

        self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

def StockReloadStyle(self):
     t = self.Theme
    m = open(f'{self.Path}/APP_FILES/PYTHON/ObjectStats/BMain.css').read()
    c = open(f'{self.Path}/APP_FILES/PYTHON/ObjectStats/B{t}.css').read()
    self.setStyleSheet(m+c)

def StockRetranslate(self):
    t = json.load(open(f'{self.Path}/APP_FILES/PYTHON/ObjectStats/CStockTranslate.json', 'r'))
    l = self.Language
    self.TitleL.setText(t['TitleL'][l])
    