""" Import PyQt5 Widgets """
from PyQt5.QtWidgets import (
    QWidget, # Simple widget, window
    QPushButton, # Simple button
    QGridLayout, # Grid layout
    QSizePolicy # Size policy 
)
#______________________________________________________________________________________________________________________
""" Import PyQt5 Core """
from PyQt5.QtCore import (
    Qt # Qt settings
)
#______________________________________________________________________________________________________________________
""" Import PyQt5 Gui """
from PyQt5.QtGui import (
    QIcon # Icon
)
#######################################################################################################################
""" Main settings Ui """
def main_settings_ui(self):
    """ Set object name """
    self.setObjectName('main_settings_widget')
    self.navi_scroll.setObjectName('navi_scroll')
    self.navi_widget.setObjectName('navi_widget')
    self.navi_user_button.setObjectName('navi_user_button')
    self.navi_style_button.setObjectName('navi_style_button')
    self.navi_sound_button.setObjectName('navi_sound_button')
    self.navi_update_button.setObjectName('navi_update_button')
    self.navi_language_button.setObjectName('navi_language_button')
    self.navi_report_button.setObjectName('navi_report_button')
    self.navi_exit_button.setObjectName('navi_exit_button')
    self.panel_right_scroll.setObjectName('panel_right_scroll')
    self.panel_right_widget.setObjectName('panel_right_widget')
    self.user_widget.setObjectName('user_widget')
    self.user_title_label.setObjectName('user_title_label')
    self.user_image_button.setObjectName('user_image_button')
    self.user_info_subtitle_label.setObjectName('user_info_subtitle_label')
    self.user_name_name_label.setObjectName('user_name_name_label')
    self.user_name_content_label.setObjectName('user_name_content_label')
    self.user_email_name_label.setObjectName('user_email_name_label')
    self.user_email_content_label.setObjectName('user_email_content_label')
    self.user_create_date_name_label.setObjectName('user_create_date_name_label')
    self.user_create_date_content_label.setObjectName('user_create_date_content_label')
    self.style_widget.setObjectName('style_widget')
    self.style_title_label.setObjectName('style_title_label')
    self.style_theme_subtitle_label.setObjectName('style_theme_subtitle_label')
    self.style_theme_d_n_name_label.setObjectName('style_theme_d_n_name_label')
    self.style_theme_d_n_content_button.setObjectName('style_theme_d_n_content_button')
    self.style_theme_themes_name_label.setObjectName('style_theme_themes_name_label')
    self.style_theme_themes_content_combobox.setObjectName('style_theme_themes_content_combobox')
    self.sound_widget.setObjectName('sound_widget')
    self.sound_title_label.setObjectName('sound_title_label')
    self.sound_button_name_label.setObjectName('sound_button_name_label')
    self.sound_button_content_button.setObjectName('sound_button_content_button')
    self.sound_alert_name_label.setObjectName('sound_alert_name_label')
    self.sound_alert_content_button.setObjectName('sound_alert_content_button')
    self.sound_notification_name_label.setObjectName('sound_notification_name_label')
    self.sound_notification_content_button.setObjectName('sound_notification_content_button')
    self.update_widget.setObjectName('update_widget')
    self.update_title_label.setObjectName('update_title_label')
    self.update_version_subtitle_label.setObjectName('update_version_subtitle_label')
    self.update_version_description_name_label.setObjectName('update_version_description_name_label')
    self.update_version_description_content_label.setObjectName('update_version_description_content_label')
    self.update_version_changelog_name_label.setObjectName('update_version_changelog_name_label')
    self.update_version_changelog_content_button.setObjectName('update_version_changelog_content_button')
    self.update_options_subtitle_label.setObjectName('update_options_subtitle_label')
    self.update_options_auto_update_name_label.setObjectName('update_options_auto_update_name_label')
    self.update_options_auto_update_content_button.setObjectName('update_options_auto_update_content_button')
    self.update_options_check_update_name_label.setObjectName('update_options_check_update_name_label')
    self.update_options_check_update_content_button.setObjectName('update_options_check_update_content_button')
    self.update_advanced_subtitle_label.setObjectName('update_advanced_subtitle_label')
    self.update_advanced_capacity_name_label.setObjectName('update_advanced_capacity_name_label')
    self.update_advanced_capacity_content_combobox.setObjectName('update_advanced_capacity_content_combobox')
    self.update_advanced_file_verification_name_label.setObjectName('update_advanced_file_verification_name_label')
    self.update_advanced_file_verification_content_label.setObjectName('update_advanced_file_verification_content_label')
    self.language_widget.setObjectName('language_widget')
    self.language_title_label.setObjectName('language_title_label')
    self.language_langauge_name_label.setObjectName('language_langauge_name_label')
    self.language_langauge_content_combobox.setObjectName('language_langauge_content_combobox')
    self.report_widget.setObjectName('report_widget')
    self.report_title_label.setObjectName('report_title_label')
    self.report_auto_report_name_label.setObjectName('report_auto_report_name_label')
    self.report_auto_report_content_button.setObjectName('report_auto_report_content_button')
    self.report_send_report_name_label.setObjectName('report_send_report_name_label')
    self.report_send_report_content_button.setObjectName('report_send_report_content_button')
#______________________________________________________________________________________________________________________
    """ Set Property """
    self.navi_scroll.setProperty('class', 'main_scroll')
    self.panel_right_scroll.setProperty('class', 'main_scroll')
    self.navi_widget.setProperty('class', 'scroll_widget')
    self.panel_right_widget.setProperty('class', 'scroll_widget')
    self.navi_user_button.setProperty('class', 'navi_button')
    self.navi_style_button.setProperty('class', 'navi_button')
    self.navi_sound_button.setProperty('class', 'navi_button')
    self.navi_update_button.setProperty('class', 'navi_button')
    self.navi_language_button.setProperty('class', 'navi_button')
    self.navi_report_button.setProperty('class', 'navi_button')
    self.navi_exit_button.setProperty('class', 'navi_button')
    self.user_widget.setProperty('class', 'panel_right_widgets')
    self.style_widget.setProperty('class', 'panel_right_widgets')
    self.sound_widget.setProperty('class', 'panel_right_widgets')
    self.update_widget.setProperty('class', 'panel_right_widgets')
    self.language_widget.setProperty('class', 'panel_right_widgets')
    self.report_widget.setProperty('class', 'panel_right_widgets')
    self.user_title_label.setProperty('class', 'panel_right_titles')
    self.style_title_label.setProperty('class', 'panel_right_titles')
    self.sound_title_label.setProperty('class', 'panel_right_titles')
    self.update_title_label.setProperty('class', 'panel_right_titles')
    self.language_title_label.setProperty('class', 'panel_right_titles')
    self.report_title_label.setProperty('class', 'panel_right_titles')
    self.user_info_subtitle_label.setProperty('class', 'panel_right_subtitles')
    self.style_theme_subtitle_label.setProperty('class', 'panel_right_subtitles')
    self.update_version_subtitle_label.setProperty('class', 'panel_right_subtitles')
    self.update_options_subtitle_label.setProperty('class', 'panel_right_subtitles')
    self.update_advanced_subtitle_label.setProperty('class', 'panel_right_subtitles')
    self.user_name_name_label.setProperty('class', 'panel_right_names')
    self.user_email_name_label.setProperty('class', 'panel_right_names')
    self.user_create_date_name_label.setProperty('class', 'panel_right_names')
    self.style_theme_d_n_name_label.setProperty('class', 'panel_right_names')
    self.style_theme_themes_name_label.setProperty('class', 'panel_right_names')
    self.sound_button_name_label.setProperty('class', 'panel_right_names')
    self.sound_alert_name_label.setProperty('class', 'panel_right_names')
    self.sound_notification_name_label.setProperty('class', 'panel_right_names')
    self.update_version_description_name_label.setProperty('class', 'panel_right_names')
    self.update_version_changelog_name_label.setProperty('class', 'panel_right_names')
    self.update_options_auto_update_name_label.setProperty('class', 'panel_right_names')
    self.update_options_check_update_name_label.setProperty('class', 'panel_right_names')
    self.update_advanced_capacity_name_label.setProperty('class', 'panel_right_names')
    self.update_advanced_file_verification_name_label.setProperty('class', 'panel_right_names')
    self.language_langauge_name_label.setProperty('class', 'panel_right_names')
    self.report_auto_report_name_label.setProperty('class', 'panel_right_names')
    self.report_send_report_name_label.setProperty('class', 'panel_right_names')
    
#______________________________________________________________________________________________________________________
