#   --- Improt ---
import json
from PyQt5.QtWidgets import (
    QSizePolicy
)
from PyQt5.QtCore import (
    Qt,
    QSize
)
from PyQt5.QtGui import (
    QPixmap,
    QIcon,
    QPainter
)
from PyQt5.QtSvg import (
    QSvgRenderer
)

def StockUi(self):
    self.setObjectName('ObjectInfoS')
    self.Widget.setObjectName('Widget')
    self.TitleL.setObjectName('TitleL')
    self.IconL.setObjectName('IconL')
    self.TickerL.setObjectName('TickerL')
    self.NameL.setObjectName('NameL')
    self.MarketL.setObjectName('MarketL')
    self.CountryL.setObjectName('CountryL')
    self.InfoW.setObjectName('InfoW')
    self.InfoTitleL.setObjectName('InfoTitleL')
    self.ActivityNameL.setObjectName('ActivityNameL')
    self.ActivityValueL.setObjectName('ActivityValueL')
    self.IndustryNameL.setObjectName('IndustryNameL')
    self.IndustryValueL.setObjectName('IndustryValueL')
    self.DateEstablishNameL.setObjectName('DateEstablishNameL')
    self.DateEstablishValueL.setObjectName('DateEstablishValueL')
    self.EmployesNameL.setObjectName('EmployesNameL')
    self.EmployesValueL.setObjectName('EmployesValueL')
    self.WebNameL.setObjectName('WebNameL')
    self.WebValueL.setObjectName('WebValueL')
    self.AdresNameL.setObjectName('AdresNameL')
    self.AdresValueL.setObjectName('AdresValueL')
    self.ManagmentW.setObjectName('ManagmentW')
    self.ManagmentTitleL.setObjectName('ManagmentTitleL')
    self.CEONameL.setObjectName('CEONameL')
    self.CEOValueL.setObjectName('CEOValueL')
    self.CFONameL.setObjectName('CFONameL')
    self.CFOValueL.setObjectName('CFOValueL')
    self.ManagmentNameL.setObjectName('ManagmentNameL')
    self.ManagmentValueL.setObjectName('ManagmentValueL')
    self.SupervisoryBoardNameL.setObjectName('SupervisoryBoardNameL')
    self.SupervisoryBoardValueL.setObjectName('SupervisoryBoardValueL')
    self.InfoW.setProperty('class', 'SubW')
    self.ManagmentW.setProperty('class', 'SubW')
    self.InfoTitleL.setProperty('class', 'SubTitle')
    self.ManagmentTitleL.setProperty('class', 'SubTitle')
    self.ActivityNameL.setProperty('class', 'Name')
    self.IndustryNameL.setProperty('class', 'Name')
    self.DateEstablishNameL.setProperty('class', 'Name')
    self.EmployesNameL.setProperty('class', 'Name')
    self.WebNameL.setProperty('class', 'Name')
    self.AdresNameL.setProperty('class', 'Name')
    self.CEONameL.setProperty('class', 'Name')
    self.CFONameL.setProperty('class', 'Name')
    self.ManagmentNameL.setProperty('class', 'Name')
    self.SupervisoryBoardNameL.setProperty('class', 'Name')
    self.ActivityValueL.setProperty('class', 'Value')
    self.IndustryValueL.setProperty('class', 'Value')
    self.DateEstablishValueL.setProperty('class', 'Value')
    self.EmployesValueL.setProperty('class', 'Value')
    self.WebValueL.setProperty('class', 'Value')
    self.AdresValueL.setProperty('class', 'Value')
    self.CEOValueL.setProperty('class', 'Value')
    self.CFOValueL.setProperty('class', 'Value')
    self.ManagmentValueL.setProperty('class', 'Value')
    self.SupervisoryBoardValueL.setProperty('class', 'Value')
    self.InfoL.addWidget(self.InfoTitleL, 0, 0, 1, 100)
    self.InfoL.addWidget(self.ActivityNameL, 1, 0, 1, 50)
    self.InfoL.addWidget(self.ActivityValueL, 1, 50, 1,50)
    self.InfoL.addWidget(self.IndustryNameL, 2, 0, 1, 50)
    self.InfoL.addWidget(self.IndustryValueL, 2, 50, 1, 50)
    self.InfoL.addWidget(self.DateEstablishNameL, 3, 0, 1, 50)
    self.InfoL.addWidget(self.DateEstablishValueL,3, 50, 1, 50)
    self.InfoL.addWidget(self.EmployesNameL, 4, 0, 1, 50)
    self.InfoL.addWidget(self.EmployesValueL, 4, 50, 1, 50)
    self.InfoL.addWidget(self.WebNameL, 5, 0, 1, 50)
    self.InfoL.addWidget(self.WebValueL, 5, 50, 1, 50)
    self.InfoL.addWidget(self.AdresNameL, 6, 0, 1, 50)
    self.InfoL.addWidget(self.AdresValueL, 6, 50 ,1, 50)
    self.InfoL.setSpacing(0)
    self.InfoL.setContentsMargins(0,0,0,0)
    for i in range(100):
        self.InfoL.setColumnStretch(i, 1)
    self.InfoW.setLayout(self.InfoL)
    self.ManagmentL.addWidget(self.ManagmentTitleL, 0, 0, 1, 100)
    self.ManagmentL.addWidget(self.CEONameL, 1, 0, 1, 50)
    self.ManagmentL.addWidget(self.CEOValueL, 1, 50, 1, 50)
    self.ManagmentL.addWidget(self.CFONameL, 2, 0, 1, 50)
    self.ManagmentL.addWidget(self.CFOValueL, 2, 50, 1, 50)
    self.ManagmentL.addWidget(self.ManagmentNameL, 3, 0, 1, 50)
    self.ManagmentL.addWidget(self.ManagmentValueL, 3, 50, 1, 50)
    self.ManagmentL.addWidget(self.SupervisoryBoardNameL, 4, 0, 1, 50)
    self.ManagmentL.addWidget(self.SupervisoryBoardValueL, 4, 50, 1, 50)
    self.ManagmentL.setSpacing(0)
    self.ManagmentL.setContentsMargins(0,0,0,0)
    for i in range(100):
        self.ManagmentL.setColumnStretch(i, 1)
    self.ManagmentW.setLayout(self.ManagmentL)
    self.Layout.addWidget(self.TitleL, 0, 0, 1,100)
    self.Layout.addWidget(self.IconL, 1, 30, 1, 40)
    self.Layout.addWidget(self.TickerL, 2, 0, 1, 100)
    self.Layout.addWidget(self.NameL, 3, 0, 1, 100)
    self.Layout.addWidget(self.MarketL, 4, 0, 1, 50)
    self.Layout.addWidget(self.CountryL,4, 50, 1, 50)
    self.Layout.addWidget(self.InfoW, 5, 0, 1, 100)
    self.Layout.addWidget(self.ManagmentW, 6, 0, 1, 100)
    self.Layout.setSpacing(0)
    self.Layout.setContentsMargins(0,0,0,0)
    for i in range(100):
        self.Layout.setColumnStretch(i, 1)
    self.Widget.setLayout(self.Layout)
    self.show()
    self.setWidget(self.Widget)
    self.setWidgetResizable(True)
    self.TitleL.setAlignment(Qt.AlignCenter)
    self.IconL.setAlignment(Qt.AlignCenter)
    self.TickerL.setAlignment(Qt.AlignCenter)
    self.NameL.setAlignment(Qt.AlignCenter)
    self.MarketL.setAlignment(Qt.AlignCenter)
    self.CountryL.setAlignment(Qt.AlignCenter)
    self.InfoTitleL.setAlignment(Qt.AlignCenter)
    self.ActivityNameL.setAlignment(Qt.AlignCenter)
    self.ActivityValueL.setAlignment(Qt.AlignCenter)
    self.IndustryNameL.setAlignment(Qt.AlignCenter)
    self.IndustryValueL.setAlignment(Qt.AlignCenter)
    self.DateEstablishNameL.setAlignment(Qt.AlignCenter)
    self.DateEstablishValueL.setAlignment(Qt.AlignCenter)
    self.EmployesNameL.setAlignment(Qt.AlignCenter)
    self.EmployesValueL.setAlignment(Qt.AlignCenter)
    self.WebNameL.setAlignment(Qt.AlignCenter)
    self.WebValueL.setAlignment(Qt.AlignCenter)
    self.AdresNameL.setAlignment(Qt.AlignCenter)
    self.AdresValueL.setAlignment(Qt.AlignCenter)
    self.ManagmentTitleL.setAlignment(Qt.AlignCenter)
    self.CEONameL.setAlignment(Qt.AlignCenter)
    self.CEOValueL.setAlignment(Qt.AlignCenter)
    self.CFONameL.setAlignment(Qt.AlignCenter)
    self.CFOValueL.setAlignment(Qt.AlignCenter)
    self.ManagmentNameL.setAlignment(Qt.AlignCenter)
    self.ManagmentValueL.setAlignment(Qt.AlignCenter)
    self.SupervisoryBoardNameL.setAlignment(Qt.AlignCenter)
    self.SupervisoryBoardValueL.setAlignment(Qt.AlignCenter)
    self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.Widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.TitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.IconL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.TickerL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.NameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.MarketL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CountryL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.InfoW.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.InfoTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ActivityNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ActivityValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.IndustryNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.IndustryValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.DateEstablishNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.DateEstablishValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.EmployesNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.EmployesValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.WebNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.WebValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.AdresNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.AdresValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ManagmentW.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ManagmentTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CEONameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CEOValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CFONameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.CFOValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ManagmentNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.ManagmentValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.SupervisoryBoardNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.SupervisoryBoardValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

def StockReloadStyle(self):
    t = self.Theme
    m = open(f'{self.Path}/APP_FILES/PYTHON/ObjectInfo/BMain.css').read()
    c = open(f'{self.Path}/APP_FILES/PYTHON/ObjectInfo/B{t}.css').read()
    self.setStyleSheet(m+c)

def StockRetranslate(self):
    t = json.load(open(f'{self.Path}/APP_FILES/PYTHON/ObjectInfo/CStockTranslate.json', 'r'))
    l = self.Language
    self.TitleL.setText(t['TitleL'][l])
    self.InfoTitleL.setText(t['InfoTitleL'][l])
    self.ActivityNameL.setText(t['ActivityNameL'][l]+':')
    self.IndustryNameL.setText(t['IndustryNameL'][l]+':')
    self.DateEstablishNameL.setText(t['DateEstablishNameL'][l]+':')
    self.EmployesNameL.setText(t['EmployesNameL'][l]+':')
    self.WebNameL.setText(t['WebNameL'][l]+':')
    self.AdresNameL.setText(t['AdresNameL'][l]+':')
    self.ManagmentTitleL.setText(t['ManagmentTitleL'][l])
    self.CEONameL.setText(t['CEONameL'][l]+':')
    self.CFONameL.setText(t['CFONameL'][l]+':')
    self.ManagmentNameL.setText(t['ManagmentNameL'][l]+':')
    self.SupervisoryBoardNameL.setText(t['SupervisoryBoardNameL'][l]+':')
