#   --- Import packages ---
import json
#   --- Import PyQt5 packages ---
from PyQt5.QtWidgets import (
    QSizePolicy
)
from PyQt5.QtCore import (
    Qt,
    QSize
)
from PyQt5.QtGui import (
    QPixmap,
    QIcon,
    QPainter
)
from PyQt5.QtSvg import (
    QSvgRenderer
)

def ui(self):
    self.setObjectName('Login_configuration_widget')
    self.title_label.setObjectName('title_label')
    self.info_label.setObjectName('info_label')
    self.left_button.setObjectName('left_button')
    self.right_button.setObjectName('right_button')
    self.navi_label.setObjectName('navi_label')
    self.left_button.setProperty('class', 'navi_button')
    self.right_button.setProperty('class', 'navi_button')
    self.layout.addWidget(self.title_label, 0, 0, 10, 100)
    self.layout.addWidget(self.info_label, 15, 0, 75, 100)
    self.layout.addWidget(self.left_button, 92, 10, 6, 10)
    self.layout.addWidget(self.right_button, 92, 80, 6, 10)
    self.layout.addWidget(self.navi_label, 92, 20, 6, 60)
    self.layout.setSpacing(0)
    self.layout.setContentsMargins(0,0,0,0)
    for enc in range(100):
        self.layout.setRowStretch(enc, 1)
        self.layout.setColumnStretch(enc, 1)
    self.setLayout(self.layout)
    self.show()
    self.title_label.setAlignment(Qt.AlignCenter)
    self.info_label.setAlignment(Qt.AlignCenter)
    self.navi_label.setAlignment(Qt.AlignCenter)
    self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.title_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.info_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.left_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.right_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.navi_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

def reload_style(self):
    self.setStyleSheet(self.main_path+'/PYTHON/login_config/c_style.css')
    # Dodać ikony

def retranslate(self):
    t = json.load(open(self.main_path+'/PYTHON/login_config/j_translate.json', 'r'))
    l = json.load(open(self.main_path+'/PYTHON/login_config/j_config.json', 'r'))['language']
    self.title_label.setText(t['title_label'][l])
    self.left_button.setText(t['left_button'][l])
    self.right_button.setText(t['right_button'][l])

def center_widget_setup_ui(self):
    self.center_widget.setObjectName('center_widget')
    self.center_layout.setSpacing(0)
    self.center_layout.setContentsMargins(0,0,0,0)
    self.center_widget.setLayout(self.center_layout)
    self.layout.addWidget(self.center_widget, 15, 0, 75, 100)
    self.center_widget.show()
    self.center_widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

def app_conf_ui(self):
    self.language_subtitle_label.setObjectName('language_subtitle_label')
    self.language_combobox.setObjectName('language_combobox')
    self.theme_subtitle_label.setObjectName('theme_subtitle_label')
    self.theme_combobox.setObjectName('theme_combobox')
    self.language_subtitle_label.setProperty('class', 'subtitle')
    self.theme_subtitle_label.setProperty('class', 'subtitle')
    self.language_combobox.setProperty('class', 'list')
    self.theme_combobox.setProperty('class', 'list')
    self.center_layout.addWidget(self.language_subtitle_label, 0, 0, 10, 50)
    self.center_layout.addWidget(self.language_combobox, 20, 20, 80, 20)
    self.center_layout.addWidget(self.theme_subtitle_label, 0, 50, 10, 50)
    self.center_layout.addWidget(self.theme_combobox, 20, 60, 80, 20)
    self.language_subtitle_label.setAlignment(Qt.AlignCenter)
    self.theme_subtitle_label.setAlignment(Qt.AlignCenter)
    self.language_subtitle_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.language_combobox.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.theme_subtitle_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.theme_combobox.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    
def app_conf_retranslate(self):
    t = json.load(open(self.main_path+'/PYTHON/login_config/j_app_conf_translate.json', 'r'))
    l = json.load(open(self.main_path+'/PYTHON/login_config/j_config.json', 'r'))['language']
    self.language_subtitle_label.setText(t['language_subtitle_label'][l])
    self.language_combobox.addItems(t['language_combobox'])
    self.theme_subtitle_label.setText(t['theme_subtitle_label'][l])
    self.theme_combobox.addItems(t['theme_combobox'])

def sub_conf_ui(self):
    self.left_button.setObjectName('left_button')
    self.center_button.setObjectName('center_button')
    self.right_button.setObjectName('right_button')
    self.left_button.setProperty('class', 'sub_button')
    self.center_button.setProperty('class', 'sub_button')
    self.right_button.setProperty('class', 'sub_button')
    self.center_layout.addWidget(self.left_button, 0, 10, 100, 15)
    self.center_layout.addWidget(self.center_button, 0, 30, 100, 40)
    self.center_layout.addWidget(self.right_button, 0, 75, 100, 15)
    self.left_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.center_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.right_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

def sub_conf_reload_style(self):
    pass
    # Add icons 

def sub_conf_retranslate(self):
    pass
    # Add text 

def list_conf_ui(self):
    self.country_subtitle_label.setObjectName('country_subtitle_label')
    self.country_search_lineedit.setObjectName('country_search_lineedit')
    self.country_scroll.setObjectName('country_scroll')
    self.country_widget.setObjectName('country_widget')
    self.country_number_label.setObjectName('country_number_label')
    self.country_icon_label.setObjectName('country_icon_label')
    self.country_ticker_label.setObjectName('country_ticker_label')
    self.country_name_label.setObjectName('country_name_label')
    self.country_add_button.setObjectName('country_add_button')
    self.country_reset_button.setObjectName('country_reset_button')
    self.country_delete_button.setObjectName('country_delete_button')
    self.country_added_scroll.setObjectName('country_added_scroll')
    self.country_added_widget.setObjectName('country_added_widget')
    self.country_added_number_label.setObjectName('country_added_number_label')
    self.country_added_icon_label.setObjectName('country_added_icon_label')
    self.country_added_ticker_label.setObjectName('country_added_ticker_label')
    self.country_added_name_label.setObjectName('country_added_name_label')
    self.country_error_label.setObjectName('country_error_label')
    self.market_subtitle_label.setObjectName('market_subtitle_label')
    self.market_search_lineedit.setObjectName('market_search_lineedit')
    self.market_scroll.setObjectName('market_scroll')
    self.market_widget.setObjectName('market_widget')
    self.market_number_label.setObjectName('market_number_label')
    self.market_icon_label.setObjectName('market_icon_label')
    self.market_ticker_label.setObjectName('market_ticker_label')
    self.market_name_label.setObjectName('market_name_label')
    self.market_add_button.setObjectName('market_add_button')
    self.marlet_reset_button.setObjectName('marlet_reset_button')
    self.market_delete_button.setObjectName('market_delete_button')
    self.market_added_scroll.setObjectName('market_added_scroll')
    self.market_added_widget.setObjectName('market_added_widget')
    self.market_added_number_label.setObjectName('market_added_number_label')
    self.market_added_icon_label.setObjectName('market_added_icon_label')
    self.market_added_ticker_label.setObjectName('market_added_ticker_label')
    self.market_added_name_label.setObjectName('market_added_name_label')
    self.market_error_label.setObjectName('market_error_label')
    self.stock_subtitle_label.setObjectName('stock_subtitle_label')
    self.stock_search_lineedit.setObjectName('stock_search_lineedit')
    self.stock_scroll.setObjectName('stock_scroll')
    self.stock_widget.setObjectName('stock_widget')
    self.stock_number_label.setObjectName('stock_number_label')
    self.stock_icon_label.setObjectName('stock_icon_label')
    self.stock_ticker_label.setObjectName('stock_ticker_label')
    self.stock_name_label.setObjectName('stock_name_label')
    self.stock_add_button.setObjectName('stock_add_button')
    self.stock_reset_button.setObjectName('stock_reset_button')
    self.stock_delete_button.setObjectName('stock_delete_button')
    self.stock_added_scroll.setObjectName('stock_added_scroll')
    self.stock_added_widget.setObjectName('stock_added_widget')
    self.stock_added_number_label.setObjectName('stock_added_number_label')
    self.stock_added_icon_label.setObjectName('stock_added_icon_label')
    self.stock_added_ticker_label.setObjectName('stock_added_ticker_label')
    self.stock_added_name_label.setObjectName('stock_added_name_label')
    self.stock_error_label.setObjectName('stock_error_label')
    self.country_subtitle_label.setProperty('class', 'subtitle')
    self.market_subtitle_label.setProperty('class', 'subtitle')
    self.stock_subtitle_label.setProperty('class', 'subtitle')
    self.country_search_lineedit.setProperty('class', 'search')
    self.market_search_lineedit.setProperty('class', 'search')
    self.stock_search_lineedit.setProperty('class', 'search')
    self.country_scroll.setProperty('class', 'scroll')
    self.country_added_scroll.setProperty('class', 'scroll')
    self.market_scroll.setProperty('class', 'scroll')
    self.market_added_scroll.setProperty('class', 'scroll')
    self.stock_scroll.setProperty('class', 'scroll')
    self.stock_added_scroll.setProperty('class', 'scroll')
    self.country_widget.setProperty('class', 'widget')
    self.country_added_widget.setProperty('class', 'widget')
    self.market_widget.setProperty('class', 'widget')
    self.market_added_widget.setProperty('class', 'widget')
    self.stock_widget.setProperty('class', 'widget')
    self.stock_add_widget.setProperty('class', 'widget')
    self.country_number_label.setProperty('class', 'number')
    self.country_added_number_label.setProperty('class', 'number')
    self.market_number_label.setProperty('class', 'number')
    self.market_added_number_label.setProperty('class', 'number')
    self.stock_number_label.setProperty('class', 'number')
    self.stock_added_number_label.setProperty('class', 'number')
    self,country_icon_label.setProperty('class', 'icon')
    self.country_added_icon_label.setProperty('class', 'icon')
    self.market_icon_label.setProperty('class', 'icon')
    self.market_added_icon_label.setProperty('class', 'icon')
    self.stock_icon_label.setProperty('class', 'icon')
    self.stock_added_icon_label.setProperty('class', 'icon')
    self,country_ticker_label.setProperty('class', 'ticker')
    self.country_added_ticker_label.setProperty('class', 'ticker')
    self.market_ticker_label.setProperty('class', 'ticker')
    self.market_added_ticker_label.setProperty('class', 'ticker')
    self.stock_ticker_label.setProperty('class', 'ticker')
    self.stock_added_ticker_label.setProperty('class', 'ticker')
    self,country_name_label.setProperty('class', 'name')
    self.country_added_name_label.setProperty('class', 'name')
    self.market_name_label.setProperty('class', 'name')
    self.market_added_name_label.setProperty('class', 'name')
    self.stock_name_label.setProperty('class', 'name')
    self.stock_added_name_label.setProperty('class', 'name')
    self.country_add_button.setProperty('class', 'controll_button')
    self.country_reset_button.setProperty('class', 'controll_button')
    self.country_delete_button.setProperty('class', 'controll_button')
    self.market_add_button.setProperty('class', 'controll_button')
    self.marlet_reset_button.setProperty('class', 'controll_button')
    self.market_delete_button.setProperty('class', 'controll_button')
    self.stock_add_button.setProperty('class', 'controll_button')
    self.stock_reset_button.setProperty('class', 'controll_button')
    self.stock_delete_button.setProperty('class', 'controll_button')
    self.country_error_label.setProperty('class', 'error')
    self.market_error_label.setProperty('class', 'error')
    self.stock_error_label.setProperty('class', 'error')
    self.center_layout.addWidget(self.country_subtitle_label, 0, 2, 10, 30)
    self.center_layout.addWidget(self.country_search_lineedit, 10, 2, 15, 30)
    self.center_layout.addWidget(self.country_scroll, 30, 0, 65, 10)
    self.center_layout.addWidget(self.country_add_button, 30, 14, 10, 2)
    self.center_layout.addWidget(self.country_reset_button, 45, 14, 10, 2)
    self.center_layout.addWidget(self.country_delete_button, 60, 14, 10, 2)
    self.center_layout.addWidget(self.country_added_scroll, 30, 20, 65, 10)
    self.center_layout.addWidget(self.country_error_label, 95, 0, 5, 30)
    self.center_layout.addWidget(self.market_subtitle_label, 0, 34, 10, 30)
    self.center_layout.addWidget(self.market_search_lineedit, 10, 34, 15, 30)
    self.center_layout.addWidget(self.market_scroll, 30, 32, 65, 10)
    self.center_layout.addWidget(self.market_add_button, 30, 46, 10, 2)
    self.center_layout.addWidget(self.marlet_reset_button, 45, 46, 10, 2)
    self.center_layout.addWidget(self.market_delete_button, 60, 46, 10, 2)
    self.center_layout.addWidget(self.market_added_scroll, 30, 52, 65, 10)
    self.center_layout.addWidget(self.market_error_label, 95, 34, 5, 30)
    self.center_layout.addWidget(self.stock_subtitle_label, 0, 68, 10, 30)
    self.center_layout.addWidget(self.stock_search_lineedit, 10, 68, 15, 30)
    self.center_layout.addWidget(self.stock_scroll, 30, 66, 65, 10)
    self.center_layout.addWidget(self.stock_add_button, 30, 80, 10, 2)
    self.center_layout.addWidget(self.stock_reset_button, 45, 80, 10, 2)
    self.center_layout.addWidget(self.stock_delete_button, 60, 80, 10, 2)
    self.center_layout.addWidget(self.stock_added_scroll, 30, 88, 65, 10)
    self.center_layout.addWidget(self.stock_error_label, 95, 66, 5, 30)
    self.country_layout.addWidget(self.country_number_label, 0, 0, 1, 10)
    self.country_layout.addWidget(self.country_icon_label, 0, 10, 1, 10)
    self.country_layout.addWidget(self.country_ticker_label, 0, 20, 1, 30)
    self.country_layout.addWidget(self.country_name_label, 0, 50, 1, 50)
    self.country_layout.setSpacing(0)
    self.country_layout.setContentsMargins(0,0,0,0)
    for enc in range(100):
        self.country_layout.setColumnStretch(enc, 1)
    self.country_widget.setLayout(self.country_layout)
    self.country_added_layout.addWidget(self.country_added_number_label, 0, 0, 1, 10)
    self.country_added_layout.addWidget(self.country_added_icon_label, 0, 10, 1, 10)
    self.country_added_layout.addWidget(self.country_added_ticker_label, 0, 20, 1, 30)
    self.country_added_layout.addWidget(self.country_name_label, 0, 50, 1, 50)
    self.country_added_layout.setSpacing(0)
    self.country_added_layout.setContentsMargins(0,0,0,0)
    for enc in range(100):
        self.country_added_layout.setColumnStretch(enc, 1)
    self.country_added_widget.setLayout(self.country_added_layout)
    self.market_layout.addWidget(self.market_number_labl , 0, 0, 1, 10)
    self.market_layout.addWidget(self.market_icon_label, 0, 10, 1, 10)
    self.market_layout.addWidget(self.market_ticker_label, 0, 20, 1, 30)
    self.market_layout.addWidget(self.market_name_label, 0, 50, 1, 50)
    self.market_layout.setSpacing(0)
    self.market_layout.setContentsMargins(0,0,0,0)
    for enc in range(100):
        self.market_layout.setColumnStretch(enc, 1)
    self.market_widget.setLayout(self.market_layout)
    self.market_added_layout.addWidget(self.market_added_name_label, 0, 0, 1, 10)
    self.market_added_layout.addWidget(self.market_added_icon_label, 0, 10, 1, 10)
    self.market_added_layout.addWidget(self.market_added_ticker_label, 0, 20, 1, 30)
    self.market_added_layout.addWidget(self.market_added_name_label, 0, 50, 1, 50)
    self.market_added_layout.setSpacing(0)
    self.market_added_layout.setContentsMargins(0,0,0,0)
    for enc in range(100):
        self.market_added_layout.setColumnStretch(enc, 1)
    self.market_added_widget.setLayout(self.market_added_layout)
    self.stock_layout.addWidget(self.stock_name_label, 0, 0, 1, 10)
    self.stock_layout.addWidget(self.stock_icon_label, 0, 10, 1, 10)
    self.stock_layout.addWidget(self.stock_ticker_label, 0, 20, 1, 30)
    self.stock_layout.addWidget(self.stock_name_label, 0, 50, 1, 50)
    self.stock_layout.setSpacing(0)
    self.stock_layout.setContentsMargins(0,0,0,0)
    for enc in range(100):
        self.stock_layout.setColumnStretch(enc, 1)
    self.stock_widget.setLayout(self.stock_layout)
    self.stock_added_layout.addWidget(self.stock_added_number_labl , 0, 0, 1, 10)
    self.stock_added_layout.addWidget(self.stock_added_icon_label, 0, 10, 1, 10)
    self.stock_added_layout.addWidget(self.stock_added_ticker_label, 0, 20, 1, 30)
    self.stock_added_layout.addWidget(self.stock_added_name_label, 0, 50, 1, 50)
    self.stock_added_layout.setSpacing(0)
    self.stock_added_layout.setContentsMargins(0,0,0,0)
    for enc in range(100):
        self.stock_added_layout.setColumnStretch(enc, 1)
    self.stock_added_widget.setLayout(self.stock_added_layout)
    self.country_scroll.setWidget(self.country_widget)
    self.country_scroll.setWidgetResizable(True)
    self.country_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
    self.country_added_scroll.setWidget(self.country_added_widget)
    self.country_added_scroll.setWidgetResizable(True)
    self.country_added_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
    self.market_scroll.setWidget(self.market_widget)
    self.market_scroll.setWidgetResizable(True)
    self.market_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
    self.market_added_scroll.setWidget(self.market_added_widget)
    self.market_added_scroll.setWidgetResizable(True)
    self.market_added_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
    self.stock_scroll.setWidget(self.stock_widget)
    self.stock_scroll.setWidgetResizable(True)
    self.stock_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
    self.stock_added_scroll.setWidget(self.stock_added_widget)
    self.stock_added_scroll.setWidgetResizable(True)
    self.stock_added_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
    self.country_subtitle_label.setAlignment(Qt.AlignCenter)
    self.country_number_label.setAlignment(Qt.AlignCenter)
    self.country_ticker_label.setAlignment(Qt.AlignCenter)
    self.country_name_label.setAlignment(Qt.AlignCenter)
    self.country_added_number_label.setAlignment(Qt.AlignCenter)
    self.country_added_ticker_label.setAlignment(Qt.AlignCenter)
    self.country_added_name_label.setAlignment(Qt.AlignCenter)
    self.country_error_label.setAlignment(Qt.AlignCenter)
    self.country_error_label.hide()
    self.market_subtitle_label.setAlignment(Qt.AlignCenter)
    self.market_number_label.setAlignment(Qt.AlignCenter)
    self.market_ticker_label.setAlignment(Qt.AlignCenter)
    self.market_name_label.setAlignment(Qt.AlignCenter)
    self.market_added_number_label.setAlignment(Qt.AlignCenter)
    self.market_added_ticker_label.setAlignment(Qt.AlignCenter)
    self.market_added_name_label.setAlignment(Qt.AlignCenter)
    self.market_error_label.setAlignment(Qt.AlignCenter)
    self.market_error_label.hide()
    self.stock_subtitle_label.setAlignment(Qt.AlignCenter)
    self.stock_number_label.setAlignment(Qt.AlignCenter)
    self.stock_ticker_label.setAlignment(Qt.AlignCenter)
    self.stock_name_label.setAlignment(Qt.AlignCenter)
    self.stock_added_number_label.setAlignment(Qt.AlignCenter)
    self.stock_added_ticker_label.setAlignment(Qt.AlignCenter)
    self.stock_added_name_label.setAlignment(Qt.AlignCenter)
    self.stock_error_label.setAlignment(Qt.AlignCenter)
    self.stock_error_label.hide()
    self.country_delete_button.setDisabled(True)
    self.market_delete_button.setDisabled(True)
    self.stock_delete_button.setDisabled(True)
    self.country_subtitle_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.country_search_lineedit.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.country_scroll.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.center_widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.country_name_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.country_icon_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.country_ticker_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.country_name_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.country_add_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.country_reset_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.country_delete_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.country_added_scroll.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.country_added_widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.country_added_number_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.country_added_icon_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.country_added_ticker_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.country_added_name_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.country_error_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.market_subtitle_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.market_search_lineedit.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.market_scroll.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.market_widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.market_number_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.market_icon_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.market_ticker_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.market_name_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.market_add_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.marlet_reset_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.market_delete_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.market_added_scroll.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.market_added_widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.market_added_number_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.market_added_icon_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.market_added_ticker_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.market_added_name_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.market_error_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.stock_subtitle_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.stock_search_lineedit.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.stock_scroll.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.stock_widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.stock_number_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.stock_icon_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.stock_ticker_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.stock_name_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.stock_add_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.stock_reset_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.stock_delete_button.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.stock_added_scroll.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.stock_added_widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.stock_added_number_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.stock_added_icon_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.stock_added_ticker_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.stock_added_name_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.stock_error_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

def list_conf_reload_style(self):
    # Dodać ikony 
    pass

def list_conf_retranslate(self):
    t = json.load(open(self.main_path+'/PYTHON/login_config/p_list_conf_translate.json', 'r'))
    l = json.load(open(self.main_path+'/CONFIG/GLOBAL/global_config.json', 'r'))['language']
    self.country_subtitle_label.setText(t['country_subtitle_label'][l])
    self.country_search_lineedit.setPlaceHolderText(t['xxx_search_lineedit'][l])
    self.country_number_label.setText('#')
    self.country_ticker_label.setText(t['xxx_ticker_label'][l])
    self.country_name_label.setText(t['xxx_name_label'][l])
    self.country_added_number_label.setText('#')
    self.country_added_ticker_label.setText(t['xxx_ticker_label'][l])
    self.country_added_name_label.setText(t['xxx_name_label'][l])
    self.market_subtitle_label.setText(t['market_subtitle_label'][l])
    self.market_search_lineedit.setPlaceHolderText(t['xxx_search_lineedit'][l])
    self.market_number_label.setText('#')
    self.market_ticker_label.setText(t['xxx_ticker_label'][l])
    self.market_name_label.setText(t['xxx_name_label'][l])
    self.market_added_number_label.setText('#')
    self.market_added_ticker_label.setText(t['xxx_ticker_label'][l])
    self.market_added_name_label.setText(t['xxx_name_label'][l])
    self.stock_subtitle_label.setText(t['stock_subtitle_label'][l])
    self.stock_search_lineedit.setPlaceHolderText(t['xxx_search_lineedit'][l])
    self.stock_number_label.setText('#')
    self.stock_ticker_label.setText(t['xxx_ticker_label'][l])
    self.stock_name_label.setText(t['xxx_name_label'][l])
    self.stock_added_number_label.setText('#')
    self.stock_added_ticker_label.setText(t['xxx_ticker_label'][l])
    self.stock_added_name_label.setText(t['xxx_name_label'][l])

def accept_settings_ui(self):
    self.regulations_scroll.setObjectName('regulations_scroll')
    self.regulations_widget.setObjectName('regulations_widget')
    self.regulations_label.setObjectName('regulations_label')
    self.center_layout.addWidget(self.regulations_scroll, 0, 20, 100, 60)
    self.regulations_layout.addWidget(self.regulations_label, 0, 0)
    self.regulations_layout.setSpacing(0)
    self.regulations_layout.setContentsMargins(0,0,0,0)
    self.regulations_widget.setLayout(self.regulations_layout)
    self.regulations_scroll.setWidget(self.regulations_widget)
    self.regulations_scroll.setWidgetResizable(True)
    self.regulations_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
    self.regulations_label.setAlignment(Qt.AlignCenter)
    self.regulations_scroll.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.regulations_widget.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.regulations_label.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

def accept_settings_reload_style(self):
    pass

def accept_settings_retranslate(self):
    t = json.load(open(self.main_path+'/PYTHON/login_config/j_accept_settings_translate.json', 'r'))
    l = json.load(open(self.main_path+'/CONFIG/GLOBAL/global_config.json', 'r'))['language']
    self.regulations_label.setText(t['regulations_label'][l])
