#   --- Import packages ---
import json
#   --- Import PyQt5 packages ---
from PyQt5.QtWidgets import (
    QSizePolicy
)
from PyQt5.QtCore import (
    Qt,
    QSize
)
from PyQt5.QtGui import (
    QIcon,
    QPixmap,
    QPainter
)
from PyQt5.QtSvg import (
    QSvgRenderer
)

def SettingsUi(self):
    self.setObjectName('SettingsW')
    self.NaviS.setObjectName('NaviS')
    self.NaviW.setObjectName('NaviW')
    self.NaviUserB.setObjectName('NaviUserB')
    self.NaviStyleB.setObjectName('NaviStyleB')
    self.NaviSoundB.setObjectName('NaviSoundB')
    self.NaviUpdateB.setObjectName('NaviUpdateB')
    self.NaviLanguageB.setObjectName('NaviLanguageB')
    self.NaviExitB.setObjectName('NaviExitB')
    self.NaviUserB.setProperty('class', 'NaviB')
    self.NaviStyleB.setProperty('class', 'NaviB')
    self.NaviSoundB.setProperty('class', 'NaviB')
    self.NaviUpdateB.setProperty('class', 'NaviB')
    self.NaviLanguageB.setProperty('class', 'NaviB')
    self.NaviExitB.setProperty('class', 'NaviB')
    self.NaviL.addWidget(self.NaviUserB)
    self.NaviL.addWidget(self.NaviStyleB)
    self.NaviL.addWidget(self.NaviSoundB)
    self.NaviL.addWidget(self.NaviUpdateB)
    self.NaviL.addWidget(self.NaviLanguageB)
    self.NaviL.setSpacing(0)
    self.NaviL.setContentsMargins(0,0,0,0)
    self.NaviW.setLayout(self.NaviL)
    self.Layout.addWidget(self.NaviS, 0, 0, 90, 20)
    self.Layout.addWidget(self.NaviExitB, 90, 0, 10, 20)
    self.Layout.setSpacing(0)
    self.Layout.setContentsMargins(0,0,0,0)
    for i in range(100):
        self.Layout.setRowStretch(i, 1)
        self.Layout.setColumnStretch(i, 1)
    self.setLayout(self.Layout)
    self.show()
    self.NaviS.setWidgetResizable(True)
    self.NaviS.setWidget(self.NaviW)
    self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.NaviS.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.NaviW.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.NaviUserB.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.NaviStyleB.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.NaviSoundB.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.NaviUpdateB.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.NaviLanguageB.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.NaviExitB.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

def SettingsReloadStyle(self):
    t = self.Theme
    m = open(f'{self.Path}/APP_FILES/PYTHON/Settings/BMain.css').read()
    c = open(f'{self.Path}/APP_FILES/PYTHON/Settings/B{self.Theme}.css').read()
    self.setStyleSheet(m+c)
    self.NaviExitB.setIcon(QIcon(load_svg(f'{self.Path}/APP_FILES/PYTHON/Settings/DExit{t}.svg', 256, 256)))
    self.NaviExitB.setIconSize(self.NaviExitB.size())

def SettingsRetranslate(self):
    t = json.load(open(f'{self.Path}/APP_FILES/PYTHON/Settings/CNaviRetranslate.json', 'r'))
    l = self.Language
    self.NaviUserB.setText(t['NaviUserB'][l])
    self.NaviStyleB.setText(t['NaviStyleB'][l])
    self.NaviSoundB.setText(t['NaviSoundB'][l])
    self.NaviUpdateB.setText(t['NaviUpdateB'][l])
    self.NaviLanguageB.setText(t['NaviLanguageB'][l])
    self.NaviExitB.setText(t['NaviExitB'][l])
   
def UserUi(self):
    self.PanelS.setObjectName('PanelS')
    self.PanelW.setObjectName('PanelW')
    self.PanelTitleL.setObjectName('PanelTitleL')
    self.UserNameNameL.setObjectName('UserNameNameL')
    self.UserNameValueL.setObjectName('UserNameValueL')
    self.UserEmailNameL.setObjectName('UserEmailNameL')
    self.UserEmailValueL.setObjectName('UserEmailValueL')
    self.UserPhoneNameL.setObjectName('UserPhoneNameL')
    self.UserPhoneValueL.setObjectName('UserPhoneValueL')
    self.UserCountryNameL.setObjectName('UserCountryNameL')
    self.UserCountryValueL.setObjectName('UserCountryValueL')
    self.UserCreateDateNameL.setObjectName('UserCreateDateNameL')
    self.UserCreateDateValueL.setObjectName('UserCreateDateValueL')
    self.UserNameNameL.setProperty('class', 'NameL')
    self.UserEmailNameL.setProperty('class', 'NameL')
    self.UserPhoneNameL.setProperty('class', 'NameL')
    self.UserCountryNameL.setProperty('class', 'NameL')
    self.UserCreateDateNameL.setProperty('class', 'NameL')
    self.UserNameValueL.setProperty('class', 'ValueL')
    self.UserEmailValueL.setProperty('class', 'ValueL')
    self.UserPhoneValueL.setProperty('class', 'ValueL')
    self.UserCountryValueL.setProperty('class', 'ValueL')
    self.UserCreateDateValueL.setProperty('class', 'ValueL')
    self.PanelL.addWidget(self.PanelTitleL, 0, 0, 1, 100)
    self.PanelL.addWidget(self.UserNameNameL, 1, 0, 1, 25)
    self.PanelL.addWidget(self.UserNameValueL, 1, 25, 1, 25)
    self.PanelL.addWidget(self.UserEmailNameL, 2, 0, 1, 25)
    self.PanelL.addWidget(self.UserEmailValueL, 2, 25, 1, 25)
    self.PanelL.addWidget(self.UserPhoneNameL, 3, 0, 1, 25)
    self.PanelL.addWidget(self.UserPhoneValueL, 3, 25, 1, 25)
    self.PanelL.addWidget(self.UserCountryNameL, 4, 0, 1, 25)
    self.PanelL.addWidget(self.UserCountryValueL, 4, 25, 1, 25)
    self.PanelL.addWidget(self.UserCreateDateNameL, 5, 0, 1, 25)
    self.PanelL.addWidget(self.UserCreateDateValueL, 5, 25, 1, 25)
    self.PanelL.setSpacing(0)
    self.PanelL.setContentsMargins(0, 0, 0, 0)
    for i in range(100):
        self.PanelL.setColumnStretch(i,1)
    self.PanelW.setLayout(self.PanelL)
    self.Layout.addWidget(self.PanelS, 0, 20, 100, 75)
    self.show()
    self.PanelS.setWidgetResizable(True)
    self.PanelS.setWidget(self.PanelW)
    self.PanelTitleL.setAlignment(Qt.AlignCenter)
    self.UserNameNameL.setAlignment(Qt.AlignCenter)
    self.UserNameValueL.setAlignment(Qt.AlignCenter)
    self.UserEmailNameL.setAlignment(Qt.AlignCenter)
    self.UserEmailValueL.setAlignment(Qt.AlignCenter)
    self.UserPhoneNameL.setAlignment(Qt.AlignCenter)
    self.UserPhoneValueL.setAlignment(Qt.AlignCenter)
    self.UserCountryNameL.setAlignment(Qt.AlignCenter)
    self.UserCountryValueL.setAlignment(Qt.AlignCenter)
    self.UserCreateDateNameL.setAlignment(Qt.AlignCenter)
    self.UserCreateDateValueL.setAlignment(Qt.AlignCenter)
    self.PanelS.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PanelW.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PanelTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.UserNameNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.UserNameValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.UserEmailNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.UserEmailValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.UserPhoneNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.UserPhoneValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.UserCountryNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.UserCountryValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.UserCreateDateNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.UserCreateDateValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

def UserRetranslate(self):
    t = json.load(open(f'{self.Path}/APP_FILES/PYTHON/Settings/CUserPageRetranslate.json', 'r'))
    l = self.Language
    self.PanelTitleL.setText(t['PanelTitleL'][l])
    self.UserNameNameL.setText(t['UserNameNameL'][l]+':')
    self.UserEmailNameL.setText(t['UserEmailNameL'][l]+':')
    self.UserPhoneNameL.setText(t['UserPhoneNameL'][l]+':')
    self.UserCountryNameL.setText(t['UserCountryNameL'][l]+':')
    self.UserCreateDateNameL.setText(t['UserCreateDateNameL'][l]+':')

def StyleUi(self):
    self.PanelS.setObjectName('PanelS')
    self.PanelW.setObjectName('PanelW')
    self.PanelTitleL.setObjectName('PanelTitleL')
    self.StyleThemeDayNightNameL.setObjectName('StyleThemeDayNightNameL')
    self.StyleThemeDayNightValueB.setObjectName('StyleThemeDayNightValueB')
    self.StyleThemeThemesNameL.setObjectName('StyleThemeThemesNameL')
    self.StyleThemeThemesValueC.setObjectName('StyleThemeThemesValueC')
    self.StyleThemeDayNightNameL.setProperty('class', 'NameL')
    self.StyleThemeThemesNameL.setProperty('class', 'NameL')
    self.StyleThemeDayNightValueB.setProperty('class', 'ValueB')
    self.StyleThemeThemesValueC.setProperty('class', 'ValueC')
    self.PanelL.addWidget(self.PanelTitleL, 0, 0, 1, 100)
    self.PanelL.addWidget(self.StyleThemeDayNightNameL, 1, 0, 1, 25)
    self.PanelL.addWidget(self.StyleThemeDayNightValueB, 1, 25, 1, 25)
    self.PanelL.addWidget(self.StyleThemeThemesNameL, 2, 0, 1, 25)
    self.PanelL.addWidget(self.StyleThemeThemesValueC, 2, 25, 1, 25)
    self.PanelL.setSpacing(0)
    self.PanelL.setContentsMargins(0, 0, 0, 0)
    for i in range(100):
        self.PanelL.setColumnStretch(i,1)
    self.PanelW.setLayout(self.PanelL)
    self.Layout.addWidget(self.PanelS, 0, 20, 100, 75)
    self.show()
    self.PanelS.setWidgetResizable(True)
    self.PanelS.setWidget(self.PanelW)
    self.PanelTitleL.setAlignment(Qt.AlignCenter)
    self.StyleThemeDayNightNameL.setAlignment(Qt.AlignCenter)
    self.StyleThemeThemesNameL.setAlignment(Qt.AlignCenter)
    self.PanelS.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PanelW.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PanelTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.StyleThemeDayNightNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.StyleThemeDayNightValueB.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.StyleThemeThemesNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.StyleThemeThemesValueC.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    
def StyleRetranslate(self):
    t = json.load(open(f'{self.Path}/APP_FILES/PYTHON/Settings/CStylePageRetranslate.json', 'r'))
    l = self.Language
    self.PanelTitleL.setText(t['PanelTitleL'][l])
    self.StyleThemeDayNightNameL.setText(t['StyleThemeDayNightNameL'][l]+':')
    self.StyleThemeThemesNameL.setText(t['StyleThemeThemesNameL'][l]+':')
    #self.StyleThemeThemesValueC.

def SoundUi(self):
    self.PanelS.setObjectName('PanelS')
    self.PanelW.setObjectName('PanelW')
    self.PanelTitleL.setObjectName('PanelTitleL')
    self.SoundNameL.setObjectName('SoundNameL')
    self.SoundValueB.setObjectName('SoundValueB')
    self.SoundNameL.setProperty('class', 'NameL')
    self.SoundValueB.setProperty('class', 'ValueB')
    self.PanelL.addWidget(self.PanelTitleL, 0, 0, 1, 100)
    self.PanelL.addWidget(self.SoundNameL, 1, 0, 1, 25)
    self.PanelL.addWidget(self.SoundValueB, 1, 25, 1, 25)
    self.PanelL.setSpacing(0)
    self.PanelL.setContentsMargins(0, 0, 0, 0)
    for i in range(100):
        self.PanelL.setColumnStretch(i,1)
    self.PanelW.setLayout(self.PanelL)
    self.Layout.addWidget(self.PanelS, 0, 20, 100, 75)
    self.show()
    self.PanelS.setWidgetResizable(True)
    self.PanelS.setWidget(self.PanelW)
    self.PanelTitleL.setAlignment(Qt.AlignCenter)
    self.SoundNameL.setAlignment(Qt.AlignCenter)
    self.PanelS.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PanelW.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PanelTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.SoundNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.SoundValueB.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

def SoundRetranslate(self):
    t = json.load(open(f'{self.Path}/APP_FILES/PYTHON/Settings/CSoundPageRetranslate.json', 'r'))
    l = self.Language
    self.PanelTitleL.setText(t['PanelTitleL'][l])
    self.SoundNameL.setText(t['SoundNameL'][l]+':')

def UpdateUi(self):
    self.PanelS.setObjectName('PanelS')
    self.PanelW.setObjectName('PanelW')
    self.PanelTitleL.setObjectName('PanelTitleL')
    self.UpdateDescriptionNameL.setObjectName('UpdateDescriptionNameL')
    self.UpdateDescriptionValueL.setObjectName('UpdateDescriptionValueL')
    self.UpdateChangelogNameL.setObjectName('UpdateChangelogNameL')
    self.UpdateChangelogValueS.setObjectName('UpdateChangelogValueS')
    self.UpdateChangelogValueW.setObjectName('UpdateChangelogValueW')
    self.UpdateDescriptionNameL.setProperty('class', 'NameL')
    self.UpdateChangelogNameL.setProperty('class', 'NameL')
    self.UpdateDescriptionValueL.setProperty('class', 'ValueL')
    self.UpdateChangelogValueS.setProperty('class', 'ValueS')
    self.UpdateChangelogValueW.setProperty('class', 'ValueW')
    self.UpdateChangelogValueL.setSpacing(0)
    self.UpdateChangelogValueL.setContentsMargins(0,0,0,0)
    self.UpdateChangelogValueW.setLayout(self.UpdateChangelogValueL)
    self.PanelL.addWidget(self.PanelTitleL, 0, 0, 1, 100)
    self.PanelL.addWidget(self.UpdateDescriptionNameL, 1, 0, 1, 25)
    self.PanelL.addWidget(self.UpdateDescriptionValueL, 1, 25, 1, 25)
    self.PanelL.addWidget(self.UpdateChangelogNameL, 2, 0, 1, 25)
    self.PanelL.addWidget(self.UpdateChangelogValueS, 2, 25, 1, 50)
    self.PanelL.setSpacing(0)
    self.PanelL.setContentsMargins(0, 0, 0, 0)
    for i in range(100):
        self.PanelL.setColumnStretch(i,1)
    self.PanelW.setLayout(self.PanelL)
    self.Layout.addWidget(self.PanelS, 0, 20, 100, 75)
    self.show()
    self.UpdateChangelogValueS.setWidgetResizable(True)
    self.UpdateChangelogValueS.setWidget(self.UpdateChangelogValueW)
    self.PanelS.setWidgetResizable(True)
    self.PanelS.setWidget(self.PanelW)
    self.PanelTitleL.setAlignment(Qt.AlignCenter)
    self.UpdateDescriptionNameL.setAlignment(Qt.AlignCenter)
    self.UpdateDescriptionValueL.setAlignment(Qt.AlignCenter)
    self.UpdateChangelogNameL.setAlignment(Qt.AlignCenter)
    self.PanelS.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PanelW.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PanelTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.UpdateDescriptionNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.UpdateDescriptionValueL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.UpdateChangelogNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.UpdateChangelogValueS.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.UpdateChangelogValueW.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

def UpdateRetranslate(self):
    t = json.load(open(f'{self.Path}/APP_FILES/PYTHON/Settings/CUpdatePageRetranslate.json', 'r'))
    l = self.Language
    self.PanelTitleL.setText(t['PanelTitleL'][l])
    self.UpdateDescriptionNameL.setText(t['UpdateDescriptionNameL'][l]+':')
    self.UpdateChangelogNameL.setText(t['UpdateChangelogNameL'][l]+':')

def LanguageUi(self):
    self.PanelS.setObjectName('PanelS')
    self.PanelW.setObjectName('PanelW')
    self.PanelTitleL.setObjectName('PanelTitleL')
    self.LanguageNameL.setObjectName('LanguageNameL')
    self.LanguageValueC.setObjectName('LanguageValueC')
    self.LanguageNameL.setProperty('class', 'NameL')
    self.LanguageValueC.setProperty('class', 'ValueC')
    self.PanelL.addWidget(self.PanelTitleL, 0, 0, 1, 100)
    self.PanelL.addWidget(self.LanguageNameL, 1, 0, 1, 25)
    self.PanelL.addWidget(self.LanguageValueC, 1, 25, 1, 25)
    self.PanelL.setSpacing(0)
    self.PanelL.setContentsMargins(0, 0, 0, 0)
    for i in range(100):
        self.PanelL.setColumnStretch(i,1)
    self.PanelW.setLayout(self.PanelL)
    self.Layout.addWidget(self.PanelS, 0, 20, 100, 75)
    self.show()
    self.PanelS.setWidgetResizable(True)
    self.PanelS.setWidget(self.PanelW)
    self.PanelTitleL.setAlignment(Qt.AlignCenter)
    self.LanguageNameL.setAlignment(Qt.AlignCenter)
    self.PanelS.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PanelW.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.PanelTitleL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.LanguageNameL.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
    self.LanguageValueC.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)

def LanguageRetranslate(self):
    t = json.load(open(f'{self.Path}/APP_FILES/PYTHON/Settings/CLanguagePageRetranslate.json', 'r'))
    l = self.Language
    self.PanelTitleL.setText(t['PanelTitleL'][l])
    self.LanguageNameL.setText(t['LanguageNameL'][l]+':')
    #self.LanguageValueC.setText(t[''][l])

def load_svg(svg_path, width, height):
    renderer = QSvgRenderer(svg_path)
    pixmap = QPixmap(width, height)
    pixmap.fill(Qt.transparent)
    painter = QPainter(pixmap)
    renderer.render(painter)
    painter.end()
    scaled_pixmap = pixmap.scaled(QSize(width, height), Qt.KeepAspectRatio, Qt.SmoothTransformation)
    return scaled_pixmap
